<?php // DONE
$subtitle = 'CY025A';
// CY-25-A DAF CONTAINER TRUCK, issued 1989
$desc = "DAF Container Truck";
$year = '1989';
include "cypage.php";

function body() {
    global $subtitle;

    show_table([
// 1. Yellow cab and chassis, yellow container with yellow base, "IPEC" tampo, Macau (AU issued as CY-9)
	['mod' => $subtitle, 'var' => '01a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'IPEC', 'cod' => '1', 'rar' => '',
            'cdt' => 'yellow, yellow chassis',
            'tdt' => 'yellow container with yellow base, IPEC tampo',
	    'nts' => 'Also produced as CY009A Var 12a',
	],
// 2. Blue cab and chassis, blue container with blue base, "Crooke's Healthcare" tampo, Macau (UK)
	['mod' => $subtitle, 'var' => '02a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => "Crooke's Healthcare", 'cod' => '1', 'rar' => '',
            'cdt' => 'blue, blue chassis',
            'tdt' => "blue container with blue base, CROOKE'S HEALTHCARE tampo",
	],
// 3. White and orange cab, black chassis, white container with black base, "Unigate" tampo, Macau (UK)
	['mod' => $subtitle, 'var' => '03a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Unigate', 'cod' => '1', 'rar' => '',
            'cdt' => 'white and orange, black chassis',
            'tdt' => 'white container with black base, UNIGATE tampo',
	],
// 4. Red cab, black chassis, red container with black base, "Royal Mail Parcels" tampo, Macau (UK)
	['mod' => $subtitle, 'var' => '04a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Royal Mail Parcels', 'cod' => '1', 'rar' => '',
            'cdt' => 'red, black chassis',
            'tdt' => 'red container with black base, ROYAL MAIL PARCELS tampo',
	],
// 5. Blue cab and chassis, blue container with blue base, "Comma Performance Oil" tampo, Macau (UK)
	['mod' => $subtitle, 'var' => '05a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Comma Performance Oil', 'cod' => '1', 'rar' => '',
            'cdt' => 'blue, blue chassis',
            'tdt' => 'blue container with blue base, COMMA PERFORMANCE OIL tampo',
	],
// 6. White cab, bright blue chassis, white container with bright blue base, "Leisure World" tampo, Macau (UK)
	['mod' => $subtitle, 'var' => '06a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Leisure World', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, bright blue chassis',
            'tdt' => 'white container with bright blue base, LEISURE WORLD tampo',
	],
// 7. White cab, blue chassis, white container with black chassis, "Pepsi Team Suzuki" tampo, Macau 
	['mod' => $subtitle, 'var' => '07a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Pepsi Team Suzuki', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, blue chassis',
            'tdt' => 'white container with black chassis, PEPSI TEAM SUZUKI tampo',
	],
// 8. White and orange cab, orange chassis, white container with orange base, "TNT IPEC" tampo, Macau (TC)
	['mod' => $subtitle, 'var' => '08a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'TNT IPEC', 'cod' => '1', 'rar' => '',
            'cdt' => 'white and orange, orange chassis',
            'tdt' => 'white container with orange base, TNT IPEC tampo',
	],
// 9. White cab, blue chassis, white container with blue base, "Pioneer" labels, Macau (UK)
	['mod' => $subtitle, 'var' => '09a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Pioneer', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, blue chassis',
            'tdt' => 'white container with blue base, PIONEER labels',
	],
// 10. Metallic gold cab and chassis, black container with black base, "Duracell" tampo (UK)
	['mod' => $subtitle, 'var' => '10a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Duracell', 'cod' => '1', 'rar' => '',
            'cdt' => 'metallic gold cab and chassis',
            'tdt' => 'black container with black base, DURACELL tampo',
	],
// 11. Yellow container, black chassis, yellow container with black base, "Zweifel Pomy Chips" tampo
	['mod' => $subtitle, 'var' => '11a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Zweifel Pomy Chips', 'cod' => '1', 'rar' => '',
            'cdt' => 'yellow, black chassis',
            'tdt' => 'yellow container with black base, ZWEIFEL POMY CHIPS tampo',
	],
// 12. Green cab and chassis, white container with black base, "M" and orange stripe tampo, Macau (SW)
	['mod' => $subtitle, 'var' => '12a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'M', 'cod' => '1', 'rar' => '',
            'cdt' => 'green, green chassis',
            'tdt' => 'white container with black base, M and orange stripe tampo',
	],
// 13. White cab, red chassis, white container with red base, "Toblerone" tampo, Macau 
	['mod' => $subtitle, 'var' => '13a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Toblerone', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, red chassis',
            'tdt' => 'white container with red base, TOBLERONE tampo',
	],
// 14. White cab, black chassis, white container with black base, "Pirelli Gripping Stuff" tampo, Macau (TC)
	['mod' => $subtitle, 'var' => '14a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Pirelli Gripping Stuff', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, black chassis',
            'tdt' => 'white container with black base, PIRELLI GRIPPING STUFF tampo',
	],
// 15. White cab, black chassis, white container with black base, "XP" tampo, Macau (TC)
	['mod' => $subtitle, 'var' => '15a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'XP', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, black chassis',
            'tdt' => 'white container with black base, XP tampo',
	],
// 16. White cab, red chassis, white container with red base, "Toblerone" tampo, Thailand 
	['mod' => $subtitle, 'var' => '16a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Toblerone', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, red chassis',
            'tdt' => 'white container with red base, TOBLERONE tampo',
	],
// 17. White cab, yellow chassis, white container with yellow base, "HB Racing" tampo, Thailand (AS)
	['mod' => $subtitle, 'var' => '17a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'HB Racing', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, yellow chassis',
            'tdt' => 'white container with yellow base, HB RACING tampo',
	],
// 18. White cab, green chassis, white container with green base, "Garden Festival Wales" tampo, Thailand (WL)(GS)
	['mod' => $subtitle, 'var' => '18a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Garden Festival Wales', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, green chassis',
            'tdt' => 'white container with green base, GARDEN FESTIVAL WALES tampo',
	    'nts' => 'Part of Special Gift Set',
	],
// 19. Brown cab, black chassis, light gray container with black chassis, "United Parcel Service" tampo, Thailand (UK)
	['mod' => $subtitle, 'var' => '19a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'United Parcel Service', 'cod' => '1', 'rar' => '',
            'cdt' => 'brown, black chassis',
            'tdt' => 'light gray container with black chassis, UNITED PARCEL SERVICE tampo',
	],
// 20. Blue cab, black chassis, red container with white chassis, "World Cup" labels, China 
// NOTE: Version 20 with either "Matchbox International" or "Mattel Inc." cast cab. All versions below with "Mattel" only.
	['mod' => $subtitle, 'var' => '20a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'World Cup', 'cod' => '1', 'rar' => '',
            'cdt' => 'blue, black chassis',
            'tdt' => 'red container with white chassis, WORLD CUP labels',
	],
// 21. White cab, blue chassis, blue container and chassis, "Kellogg's" and cartoon characters labels, China (ROW)
	['mod' => $subtitle, 'var' => '21a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'China, MATTEL',
	    'liv' => "Kellogg's", 'cod' => '1', 'rar' => '',
            'cdt' => 'white, blue chassis',
            'tdt' => "blue container and chassis, KELLOGG'S and cartoon characters labels",
	],
// 22. Red cab, black chassis, white container and chassis, "McDonald's" labels, China (ROW)
	['mod' => $subtitle, 'var' => '22a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'China, MATTEL',
	    'liv' => "McDonald's", 'cod' => '1', 'rar' => '',
            'cdt' => 'red, black chassis',
            'tdt' => "white container and chassis, MCDONALD'S labels",
	],
// 23. Red cab, black chassis, white container and base, "Melde" labels, China (C2)
	['mod' => $subtitle, 'var' => '23a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'China, MATTEL',
	    'liv' => 'Melde', 'cod' => '2', 'rar' => '4',
            'cdt' => 'red, black chassis',
            'tdt' => 'white container and base, MELDE labels',
	],
// 24. Red cab, black chassis, red container and base, "At Home, Too! Coca Cola" labels, China and "Mattel", antennas cast, chrome disc with rubber tires (PC)
	['mod' => $subtitle, 'var' => '24a',
	    'cab' => 'MB340', 'tlr' => 'Box', 'mfg' => 'China, MATTEL',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '',
            'cdt' => 'red, black chassis',
            'tdt' => 'red container and base, AT HOME, TOO! COCA COLA labels',
	],

	['mod' => $subtitle, 'var' => '25a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '',
            'cdt' => 'red, black chassis, painted windows',
            'tdt' => 'black container, ENJOY THE REAL THING',
	],
	['mod' => $subtitle, 'var' => '26a',
	    'cab' => 'MB340', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, red chassis',
            'tdt' => 'COCA COLA CALENDAR GIRLS JAN/FED',
	],
	['mod' => $subtitle, 'var' => '27a',
	    'cab' => 'MB340', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, gray chassis',
            'tdt' => 'COCA COLA CALENDAR GIRLS JULY/AUGUST',
	],
	['mod' => $subtitle, 'var' => 'C3a',
	    'cab' => 'MB183', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Royal Mail', 'cod' => '3', 'rar' => '',
            'cdt' => 'red, black chassis',
            'tdt' => 'red container, ROYAL MAIL PARCEL FORCE',
	],
    ]);
}
?>
