<?php // DONE
$subtitle = 'CY027A';
// CY-27-A MACK CONTAINER TRUCK, issued 1990
$desc = "Mack Box Trailer";
$year = '1990';
include "cypage.php";

function body() {
    global $subtitle;

// NOTE: All models with 8-spoke wheels and no antennas cast unless otherwise noted.
    show_table([
// 1. White cab, black chassis, white container with black base, "The Greatest Name In Trucks-Mack" labels, Macau
	['mod' => $subtitle, 'var' => '01a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'Mack', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, black chassis',
            'tdt' => 'white container with black base, THE GREATEST NAME IN TRUCKS-MACK labels',
	],
// 2. Chrome plated cab, black chassis, black container with black base, "Celebrating A Decade of Matchbox Conventions 1991" labels, Macau (C2)
	['mod' => $subtitle, 'var' => '02a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'Macau',
	    'liv' => 'none', 'cod' => '2', 'rar' => '',
            'cdt' => 'chrome plated, black chassis',
            'tdt' => 'black container with black base, CELEBRATING A DECADE OF MATCHBOX CONVENTIONS 1991 labels',
	],
// 3. Black cab and chassis, black container with black base, "Body Glove" labels, Thailand
	['mod' => $subtitle, 'var' => '03a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Body Glove', 'cod' => '1', 'rar' => '',
            'cdt' => 'black, black chassis',
            'tdt' => 'black container with black base, BODY GLOVE labels',
	],
// 4. Black cab, blue chassis, blue container with black base, "Oreo" labels, Thailand
	['mod' => $subtitle, 'var' => '04a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Oreo', 'cod' => '1', 'rar' => '',
            'cdt' => 'black cab, blue chassis',
            'tdt' => 'blue container with black base, OREO labels',
	],
// 5. White cab, black chassis, white container with white base, "Nothing Else Is A Pepsi" labels, Thailand
	['mod' => $subtitle, 'var' => '05a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Pepsi', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, black chassis',
            'tdt' => 'white container with white base, NOTHING ELSE IS A PEPSI labels',
	],
// 6. White cab, black chassis, white container with white base, "Fed Ex" labels, Thailand
	['mod' => $subtitle, 'var' => '06a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Fed Ex', 'cod' => '1', 'rar' => '',
            'cdt' => 'white, black chassis',
            'tdt' => 'white container with white base, FED EX labels',
	],
// 7. Blue cab and chassis, blue container with blue base, "Planters" labels, China
	['mod' => $subtitle, 'var' => '07a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Planters', 'cod' => '1', 'rar' => '',
            'cdt' => 'blue, blue chassis',
            'tdt' => 'blue container with blue base, PLANTERS labels',
	],

	['mod' => $subtitle, 'var' => '08a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Planters', 'cod' => '1', 'rar' => '',
            'cdt' => 'blue, black chassis',
            'tdt' => 'blue container with blue base, PLANTERS labels',
	],
	['mod' => $subtitle, 'var' => '09a',
	    'cab' => 'MB311', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Haagen-Daz', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '10a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Matchbox', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '11a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Ringling Bros', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],

	['mod' => $subtitle, 'var' => '12a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Ben and Jerry', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '13a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Kroger', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '14a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Safeway', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '15a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Lucky', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '16a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Smiths', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '17a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '19a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Medle', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	],
	['mod' => $subtitle, 'var' => '21a',
	    'cab' => 'MB202', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Ben and Jerry', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	    'nts' => "Available only from Ben and Jerry's",
	],
    ]);
}
?>
