<?php // DONE
$subtitle = 'CY039A';
// CY-39-A FORD AEROMAX BOX TRUCK, issued 1994
$desc = "Aeromax Box Trailer";
$year = '1994';
include "cypage.php";

function body() {
    global $subtitle;

// NOTE: All models with 8-spoke wheels, no antennas cast unless otherwise noted
// NOTE: Due to the fluctuating Nascar market and the "dumping" of products into close-out stores, please consult Nascar related magazines for any changes in prices that may occur.
    show_table([
// 1. White cab with black chassis, white container with white base, "Pepsi/Diet Pepsi" labels
	['mod' => $subtitle, 'var' => '001a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Pepsi', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'white container, white base, PEPSI/DIET PEPSI labels',
	],
// 2. Yellow cab with black chassis, yellow container with yellow base, "Cheerios" labels
	['mod' => $subtitle, 'var' => '002a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Cheerios', 'cod' => '1', 'rar' => '2',
            'cdt' => 'yellow, black chassis',
            'tdt' => 'yellow container, yellow base, CHEERIOS labels ',
	],
// 3. Red cab with red chassis, red container with red base, "Heinz Tomato Ketchup Squeezable!" labels (UK)
	['mod' => $subtitle, 'var' => '003a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Heinz', 'cod' => '1', 'rar' => '2',
            'cdt' => 'red',
            'tdt' => 'red container, red base, HEINZ TOMATO KETCHUP SQUEEZABLE! labels',
	],
// 4. Blue cab with blue chassis, blue container with blue base, "Oreo" labels, Thailand
	['mod' => $subtitle, 'var' => '004a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Oreo', 'cod' => '1', 'rar' => '2',
            'cdt' => 'blue',
            'tdt' => 'blue container, blue base, OREO labels',
	],
// 5. Dark blue cab with dark blue chassis, dark blue container and base, "Hawaiian Punch" labels, Thailand
	['mod' => $subtitle, 'var' => '005a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Hawaiian Punch', 'cod' => '1', 'rar' => '2',
            'cdt' => 'dark blue',
            'tdt' => 'dark blue container and base, HAWAIIAN PUNCH labels',
	],
// 6. Orange cab with black chassis, orange container and base, "Honey Nut Cheerios" labels, Thailand
	['mod' => $subtitle, 'var' => '006a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Cheerios', 'cod' => '1', 'rar' => '2',
            'cdt' => 'orange, black chassis',
            'tdt' => 'orange container and base, HONEY NUT CHEERIOS labels',
	],
// 7. Silver/gray cab with black chassis, white container and base, "Pepsi/Diet Pepsi" labels, Thailand
	['mod' => $subtitle, 'var' => '007a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Pepsi', 'cod' => '1', 'rar' => '2',
            'cdt' => 'silver-gray, black chassis',
            'tdt' => 'white container and base, PEPSI/DIET PEPSI labels',
	],
// 8. White cab with black chassis, orange container with white chassis, "Honey Nut Cheerios" labels, Thailand
	['mod' => $subtitle, 'var' => '008a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Cheerios', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'orange container, white chassis, HONEY NUT CHEERIOS labels',
	],
// 9. White cab with blue chassis, blue container with white chassis, "Hawaiian Punch" labels, Thailand
	['mod' => $subtitle, 'var' => '009a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Hawaiian Punch', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, blue chassis',
            'tdt' => 'blue container, white chassis, HAWAIIAN PUNCH labels',
	],
// 10. Black cab with blue chassis, blue container with black base, "Oreo" labels, Thailand
	['mod' => $subtitle, 'var' => '010a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Oreo', 'cod' => '1', 'rar' => '2',
            'cdt' => 'black, blue chassis',
            'tdt' => 'blue container, black base, OREO labels',
	],
// 11. White cab with black chassis, white container and base, "Fed Ex" labels, Thailand
	['mod' => $subtitle, 'var' => '011a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'Thailand',
	    'liv' => 'Fed Ex', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'white container and base, FED EX labels',
	],
// 12. White cab with black chassis, white container with black base, "Fed Ex" labels, China
	['mod' => $subtitle, 'var' => '012a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Fed Ex', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'white container, black base, FED EX labels',
	],
// 13. White cab and chassis, white container and base, "Nothing Else Is A Pepsi" labels, China
	['mod' => $subtitle, 'var' => '013a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Pepsi', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, NOTHING ELSE IS A PEPSI labels',
	],
// 14. Black cab with blue chassis, blue container with black base, "Oreo" labels, China
	['mod' => $subtitle, 'var' => '014a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Oreo', 'cod' => '1', 'rar' => '2',
            'cdt' => 'black, blue chassis',
            'tdt' => 'blue container,black base, OREO labels',
	],
// 15. Black cab and chassis, black container and base, "Body Glove" labels, China
	['mod' => $subtitle, 'var' => '015a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Body Glove Ex', 'cod' => '1', 'rar' => '2',
            'cdt' => 'black',
            'tdt' => 'black, BODY GLOVE labels',
	],
// 16. Green cab, black chassis, green container and base, "Collector's Choice Upper Deck" labels, China
	['mod' => $subtitle, 'var' => '016a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Upper Deck', 'cod' => '1', 'rar' => '2',
            'cdt' => 'green, black chassis',
            'tdt' => "green, COLLECTOR'S CHOICE UPPER DECK labels",
	],
// 17. White cab and chassis, white container and base, "Barnes Van Lines" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '017a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Barnes', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, BARNES VAN LINES tampo',
	],
// 18. White cab and chassis, white container and base, "Oh What Those Oats Can Do!" labels, China (ASAP)
	['mod' => $subtitle, 'var' => '018a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => '', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, OH WHAT THOSE OATS CAN DO! labels',
	],
// 19. White cab and chassis, white container and base, "Ryder Transportation Services" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '019a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Ryder', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, RYDER TRANSPORTATION SERVICES tampo',
	],
// 20. White cab and chassis, white container and base, "Pocahontas PFG" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '020a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Pocahontas', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, POCAHONTAS PFG tampo',
	],
// 21. White cab and chassis, white container and base, no labels, China (ASAP blank)
	['mod' => $subtitle, 'var' => '021a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'none', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, no labels',
	],
// 22. White cab and chassis, white container and base, "Atlas Van Lines-Thomas of California" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '022a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Atlas Van Lines', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, ATLAS VAN LINES-THOMAS OF CALIFORNIA tampo',
	],
// 23. White cab and chassis, white container and base, "International Airport Center 1-888-Lease-Us" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '023a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'International Airport Center', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, INTERNATIONAL AIRPORT CENTER 1-888-LEASE-US tampo',
	],
// 24. White cab and chassis, white container and base, "McLane Distribution Services" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '024a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'McLane', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, MCLANE DISTRIBUTION SERVICES tampo',
	],
// 25. White cab and chassis, white container and base, "Castle-berry's" tampo, China (ASAP)(OP)
	['mod' => $subtitle, 'var' => '025a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => "Castleberry's", 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => "white, CASTLE-BERRY'S tampo",
	],
// 26. White cab and chassis, white container and base, "Austex" tampo, China (ASAP)(OP)
	['mod' => $subtitle, 'var' => '026a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Austex', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, AUSTEX tampo',
	],
// 27. Pale red cab, black chassis, red container, black base, "Coca-Cola" with Santa Claus labels, China, rubber tires (US)
	['mod' => $subtitle, 'var' => '027a',
	    'cab' => 'MB308', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '2',
            'cdt' => 'pale red, black chassis',
            'tdt' => 'red container, black base, COCA-COLA with Santa Claus labels',
	],
// 28. White cab and chassis, white container and base, "Klockner Optima Waste-free Films" labels, China (ASAP)
	['mod' => $subtitle, 'var' => '028a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Klockner', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, KLOCKNER OPTIMA WASTE-FREE FILMS labels',
	],
// 29. White cab, black chassis, white container and base, "K-B Toys" tampo, China, rubber tires, antennas cast (GC)
	['mod' => $subtitle, 'var' => '029a',
	    'cab' => 'MB308', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'K-B', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'white, K-B TOYS tampo',
	],
// 30. White cab and chassis, white container and base, "Super Pretzel" labels, China (US)(OP)
	['mod' => $subtitle, 'var' => '030a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Super Pretzel', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, SUPER PRETZEL labels',
	],
// 31. White cab, black chassis, white container and base, "Midas Auto Systems Experts" tampo, China, rubber tires, antennas cast (PC)
	['mod' => $subtitle, 'var' => '031a',
	    'cab' => 'MB308', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Midas', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'white, MIDAS AUTO SYSTEMS EXPERTS tampo',
	],
// 32. Blue cab, black chassis, blue container and base, "Goodyear #1 in Tires" tampo, China, rubber tires, antennas cast (PC)
	['mod' => $subtitle, 'var' => '032a',
	    'cab' => 'MB308', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Goodyear', 'cod' => '1', 'rar' => '2',
            'cdt' => 'blue, black chassis',
            'tdt' => 'blue, GOODYEAR #1 IN TIRES tampo',
	],
// 33. White cab and chassis, white container and base, "Mobile Process Technology" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '033a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Mobile Process Technology', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, MOBILE PROCESS TECHNOLOGY tampo',
	],
// 34. White cab and chassis, white container and base, "Metal Industries/Capitol" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '034a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Metal Indstries', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, METAL INDUSTRIES/CAPITOL tampo',
	],
// 35. White cab, black chassis, powder blue container, white base, "Coca-Cola" with polar bear labels, China
	['mod' => $subtitle, 'var' => '035a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'powder blue container, white base, COCA-COLA with polar bear labels',
	],
// 36. White cab and chassis, white container and base, "PYA/ Monarch Foodservice Distributors" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '036a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'PYA', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, PYA/ MONARCH FOODSERVICE DISTRIBUTORS tampo',
	],
// 37. White cab and chassis, white container and base, "Monarch Foodservice Distributors" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '037a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Monarch', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, MONARCH FOODSERVICE DISTRIBUTORS tampo',
	],
// 38. White cab and chassis, white container and base, "EFI-Set your ideas on Fiery" labels, China (ASAP)
	['mod' => $subtitle, 'var' => '038a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'EFI', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, EFI-SET YOUR IDEAS ON FIERY labels',
	],
// 39. White cab and chassis, white container and base, "Albertsons" labels, China (US)
	['mod' => $subtitle, 'var' => '039a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Albertsons', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, ALBERTSONS labels',
	],
// 40. White cab and chassis, white container and base, "Rite Screen" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '040a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Rite Screen', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, RITE SCREEN tampo',
	],
// 41. White cab and chassis, white container and base, "Ml Metals" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '041a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'M1 Metals', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, ML METALS tampo',
	],
// 42. White cab and chassis, white container and base, "Ml Plastics" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '042a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'M1 Plastics', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, ML PLASTICS tampo',
	],
// 43. White cab and chassis, white container and base, "Ml Home Products" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '043a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'M1 Home Products', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, ML HOME PRODUCTS tampo',
	],
// 44. Bright blue cab and chassis, bright blue container and base, "Toys R Us-50 Years Forever Fun" labels, China, rubber tires, antennas cast (TRU-PC)
	['mod' => $subtitle, 'var' => '044a',
	    'cab' => 'MB308', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Toys R Us', 'cod' => '1', 'rar' => '2',
            'cdt' => 'bright blue',
            'tdt' => 'bright blue, TOYS R US-50 YEARS FOREVER FUN labels',
	],
// 45. Red cab, black chassis, red container and base, "Coca Cola" with Santa Claus labels, China (US)
	['mod' => $subtitle, 'var' => '045a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '2',
            'cdt' => 'red, black chassis',
            'tdt' => 'red, COCA COLA with Santa Claus labels',
	],
// 46. White cab and chassis, white container and base, "Simplot" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '046a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Simplot', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, SIMPLOT tampo',
	],
// 47. White cab, black chassis, white container and base, "Vons Seafood" labels, China (US)
	['mod' => $subtitle, 'var' => '047a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Vons', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'white, VONS SEAFOOD labels',
	],
// 48. White cab, black chassis, powder blue container, white base, "Coca Cola" labels, China and "Mattel"
	['mod' => $subtitle, 'var' => '048a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China, MATTEL',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white, black chassis',
            'tdt' => 'powder blue container, white base, COCA COLA labels',
	],
// 49. Dark purple body, white chassis, white container and chassis, "Taco Bell" labels, China and "Mattel"
	['mod' => $subtitle, 'var' => '049a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China, MATTEL',
	    'liv' => 'Taco Bell', 'cod' => '1', 'rar' => '2',
            'cdt' => 'dark purple body, white chassis',
            'tdt' => 'white, TACO BELL labels',
	],
// 50. White cab and chassis, blue container and chassis, "Kellogg's" and cartoon characters labels, China and "Mattel"
	['mod' => $subtitle, 'var' => '050a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China, MATTEL',
	    'liv' => "Kellogg's", 'cod' => '1', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => "blue, KELLOGG'S and cartoon characters labels",
	],
// 51. Red cab, black chassis, red container, black chassis, "Coca Cola" and Santa labels, China and "Mattel" (US)
	['mod' => $subtitle, 'var' => '051a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China, MATTEL',
	    'liv' => 'Coca-Cola', 'cod' => '1', 'rar' => '2',
            'cdt' => 'red, black chassis',
            'tdt' => 'red container, black chassis, COCA COLA and Santa labels',
	],
// 52. White cab and chassis, white container and chassis, "Oh What those Oats can do!" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '052a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => '', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, OH WHAT THOSE OATS CAN DO! tampo',
	],
// 53. White cab and chassis, white container and chassis, "At A Glance-Millennium" labels, China (ASAP)
	['mod' => $subtitle, 'var' => '053a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => '', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, AT A GLANCE-MILLENNIUM labels',
	],
// 54. White cab and chassis, white container and chassis, "Ian Patrick Mullaney...has rolled in early" (right side only) tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '054a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => '', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, IAN PATRICK MULLANEY...HAS ROLLED IN EARLY (right side only) tampo',
	],
// 55. White cab and chassis, white container and base, "Alaska Airlines" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '055a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Alaska Airlines', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, ALASKA AIRLINES tampo',
	],
// 56. White cab and chassis, white container and base, "RCA-changing entertainment again" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '056a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'RCA', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, RCA-CHANGING ENTERTAINMENT AGAIN tampo',
	],
// 57. White cab and chassis, white container and base, "Mervyn's Community Closest" labels, China (ASAP)
	['mod' => $subtitle, 'var' => '057a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => "Mervyn's", 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => "white, MERVYN'S COMMUNITY CLOSEST labels",
	],
// 58. White cab and chassis, white container and base, "The Pepsi Bottling Company" (blue background) labels, China (ASAP)
	['mod' => $subtitle, 'var' => '058a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Pepsi', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, THE PEPSI BOTTLING COMPANY (blue background) labels',
	],
// 59. White cab and chassis, white container and base, "The Pepsi Bottling Company" (white background) labels, China (ASAP)
	['mod' => $subtitle, 'var' => '059a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Pepsi', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, THE PEPSI BOTTLING COMPANY (white background) labels',
	],
// 60. White cab and chassis, white container and base, "Ceco Door Products" labels, China (ASAP)
	['mod' => $subtitle, 'var' => '060a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Ceco', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, CECO DOOR PRODUCTS labels',
	],
// 61. White cab and chassis, white container and base, "Parcel Direct" labels, China (ASAP)
	['mod' => $subtitle, 'var' => '061a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Parcel Direct', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, PARCEL DIRECT labels',
	],
// 62. White cab and chassis, white container and base, "Black Dog DVD Express" (left side only) tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '062a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Black Dog', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, BLACK DOG DVD EXPRESS (left side only) tampo',
	],
// 63. Orange and blue cab, blue chassis, white container and base, "Roadway" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '063a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Roadway', 'cod' => '2', 'rar' => '2',
            'cdt' => 'orange and blue, blue chassis',
            'tdt' => 'white, ROADWAY tampo',
	],
// 64. White cab and chassis, white container and base, "The Celebrity Train" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '064a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Celebrity Train', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, THE CELEBRITY TRAIN tampo',
	],
// 65. White cab and chassis, white container and base, "Klondike Good Humor Popsicle" labels, China (ASAP)
	['mod' => $subtitle, 'var' => '065a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Klondike', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, KLONDIKE GOOD HUMOR POPSICLE labels',
	],
// 66. White cab and chassis, white container and base, "Matchbox Books" labels, China (CLR)
	['mod' => $subtitle, 'var' => '066a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Matchbox Books', 'cod' => '1', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, MATCHBOX BOOKS labels',
	],
// 67. White cab and chassis, white container and base, "Sanford Shelbeyville Distribution Center" (left side only) tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '067a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Sanford Shelbyville Distribution Center', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, SANFORD SHELBEYVILLE DISTRIBUTION CENTER (left side only) tampo',
	],
// 68. White cab and chassis, white container and base, "Ship McQuaide" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '068a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Ship McQuaide', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, SHIP MCQUAIDE tampo',
	],
// 69. White cab and chassis, white container and base, "Fieldbrook Farms" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '069a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Fieldbrook Farms', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, FIELDBROOK FARMS tampo',
	],
// 70. White cab and chassis, white container and base, "Another Load of Express Cargo- Alaska Airlines" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '070a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Alaska Airlines', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, ANOTHER LOAD OF EXPRESS CARGO- ALASKA AIRLINES tampo',
	],
// 71. Orange and blue cab, blue chassis, white container and base, none labels, China (ASAP blank)
	['mod' => $subtitle, 'var' => '071a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'none', 'cod' => '2', 'rar' => '2',
            'cdt' => 'orange and blue, blue chassis',
            'tdt' => 'white, none labels',
	],
// 72. Orange and blue cab, blue chassis, white container and base, "We've Scored! 20th Annual Matchbox USA Convention and Toy Show" tampo, China (CLR)
	['mod' => $subtitle, 'var' => '072a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => '', 'cod' => '1', 'rar' => '2',
            'cdt' => 'orange and blue, blue chassis',
            'tdt' => "white, WE'VE SCORED! 20TH ANNUAL MATCHBOX USA CONVENTION AND TOY SHOW tampo",
	],
// 73. White cab and chassis, white container and base, "Nazareth Pallet Co." tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '073a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Nazareth Pallet Co.', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, NAZARETH PALLET CO. tampo',
	],
// 74. White cab and chassis, white container and base, "CIA Truck Adjusting...for the long haul" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '074a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'CIA Truck Adjusting', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, CIA TRUCK ADJUSTING...FOR THE LONG HAUL tampo',
	],
// 75. White cab and chassis, white container and base, "Guida's Milk and Ice Cream" tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '075a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => "Guida's", 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => "white, GUIDA'S MILK AND ICE CREAM tampo",
	],
// 76. White cab and chassis, white container and base, "Bulldog Castor Co." tampo, China (ASAP)
	['mod' => $subtitle, 'var' => '076a',
	    'cab' => 'MB214', 'tlr' => 'Box', 'mfg' => 'China',
	    'liv' => 'Bulldog', 'cod' => '2', 'rar' => '2',
            'cdt' => 'white',
            'tdt' => 'white, BULLDOG CASTOR CO. tampo',
	],
    ]);
}
?>
