<?php // DONE
$subtitle = 'CY104A';
// CY-104-A KENWORTH SUPERSTAR TRANSPORTER, issued 1989
$desc = "Kenworth Superstar Transporter";
$year = '1989';
include "cypage.php";

function body() {
    global $subtitle;

    show_table([
// 1. White cab with "STP" logo, white container, black base, "Richard Petty/STP" labels (WR)
	['mod' => $subtitle, 'var' => '01a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'STP', 'cod' => '2', 'rar' => '',
            'cdt' => 'white, STP logo',
            'tdt' => "white container, black base, RICHARD PETTY/STP labels",
	],
// 2. White cab, white container, black base, "Neil Bonnett/Citgo" labels (WR)
	['mod' => $subtitle, 'var' => '02a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Citgo', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, NEIL BONNETT/CITGO labels",
	],
// 3. White cab, white container, black base, "Hardee's Racing" labels (WR)
	['mod' => $subtitle, 'var' => '03a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Hardees", 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, HARDEE'S RACING labels",
	],
// 4. Black cab, black container, silver-gray base, "Good-wrench Racing Team" labels (WR)
	['mod' => $subtitle, 'var' => '04a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Goodwrench', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, silver-gray base, GOOD-WRENCH RACING TEAM labels",
	],
// 5. White cab, dark blue container, black base, "Goodyear Racing" labels 
	['mod' => $subtitle, 'var' => '05a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Goodyear', 'cod' => '1', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "dark blue container, black base, GOODYEAR RACING labels",
	],
// 6. Black cab, black container, black base, "Exxon 51" labels (DT)
	['mod' => $subtitle, 'var' => '06a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Exxon', 'cod' => '1', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, EXXON 51 labels",
            'nts' => 'Days of Thunder',
	],
// 7. Black and green cab, black container, black base, "Mello Yello 51" labels (DT)
	['mod' => $subtitle, 'var' => '07a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Mello Yello', 'cod' => '1', 'rar' => '',
            'cdt' => 'black and green',
            'tdt' => "black container, black base, MELLO YELLO 51 labels",
            'nts' => 'Days of Thunder',
	],
// 8. Orange cab, orange container, black base, "Hardees 18" labels (DT)
	['mod' => $subtitle, 'var' => '08a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Hardees', 'cod' => '1', 'rar' => '',
            'cdt' => 'orange',
            'tdt' => "orange container, black base, HARDEES 18 labels",
            'nts' => 'Days of Thunder',
	],
// 9. Pink cab, white container, black base, "Superflo 46" labels (DT)
	['mod' => $subtitle, 'var' => '09a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Superflo', 'cod' => '1', 'rar' => '',
            'cdt' => 'pink',
            'tdt' => "white container, black base, SUPERFLO 46 labels",
            'nts' => 'Days of Thunder',
	],
// 10. White cab, white container, black base, "City Chevrolet" labels (DT)
	['mod' => $subtitle, 'var' => '10a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'City Chevrolet', 'cod' => '1', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, CITY CHEVROLET labels",
            'nts' => 'Days of Thunder',
	],
// 11. White cab with red and blue tampo, white container, black base, "Richard Petty/STP" labels (WR)
	['mod' => $subtitle, 'var' => '11a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'STP', 'cod' => '2', 'rar' => '',
            'cdt' => 'white, red and blue tampo',
            'tdt' => "white container, black base, RICHARD PETTY/STP labels",
	],
// 12. Black cab, black container, black base, "Goodwrench Racing Team" labels (WR)
	['mod' => $subtitle, 'var' => '12a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Goodwrench', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, GOODWRENCH RACING TEAM labels",
	],
// 13. Gold cab without "6" on doors, gold container, black base, "Folgers" labels (WR)
	['mod' => $subtitle, 'var' => '13a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Folgers', 'cod' => '2', 'rar' => '',
            'cdt' => 'gold without 6 on doors',
            'tdt' => "gold container, black base, FOLGERS labels",
        ],
// 14. White cab, white container, black base, "Trop Artie" with "Dick Trickle" labels (WR)
	['mod' => $subtitle, 'var' => '14a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Trop Artic', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, TROP ARTIC with DICK TRICKLE labels",
        ],
// 15. White and blue cab, white container, black base, "Valvoline" labels (IN)
	['mod' => $subtitle, 'var' => '15a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Valvoline', 'cod' => '1', 'rar' => '',
            'cdt' => 'white and blue',
            'tdt' => "white container, black base, VALVOLINE labels",
        ],
// 16. Yellow cab, yellow container, black base, "Pennzoil 4" labels (IN)
	['mod' => $subtitle, 'var' => '16a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Pennzoil', 'cod' => '1', 'rar' => '',
            'cdt' => 'yellow',
            'tdt' => "yellow container, black base, PENNZOIL 4 labels",
        ],
// 17. Gold cab with "6" on doors, gold container, black base, "Folgers" labels (WR)
	['mod' => $subtitle, 'var' => '17a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Folgers', 'cod' => '2', 'rar' => '',
            'cdt' => 'gold cab with 6 on doors',
	    'tdt' => "gold container, black base, FOLGERS labels",
        ],
// 18. Black cab, black container, black base, "Goodwrench Racing Team" with team car depicted on sides labels (WR)
	['mod' => $subtitle, 'var' => '18a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Goodwrench', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, GOODWRENCH RACING TEAM with team car depicted on sides labels",
        ],
// 19. Dark blue cab, dark blue container, black base, "94 Sunoco" without "Sterling Marlin" on labels (WR)
	['mod' => $subtitle, 'var' => '19a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Sunoco', 'cod' => '2', 'rar' => '',
            'cdt' => 'dark blue',
            'tdt' => "dark blue container, black base, 94 SUNOCO without STERLING MARLIN on labels",
        ],
// 20. Dark blue cab, dark blue container, black base, "94 Sunoco" with "Sterling Marlin" on labels (WR)
	['mod' => $subtitle, 'var' => '20a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Sunoco', 'cod' => '2', 'rar' => '',
            'cdt' => 'dark blue',
            'tdt' => "dark blue container, black base, 94 SUNOCO with STERLING MARLIN on labels",
        ],
// 21. White cab, white container, black base, "Crown Moroso" labels (WR)
	['mod' => $subtitle, 'var' => '21a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Crown', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, CROWN MOROSO labels",
        ],
// 22. Black cab, black container, black base, "Texaco Havoline/Davey Allison" labels (WR)
	['mod' => $subtitle, 'var' => '22a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Texaco', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, TEXACO HAVOLINE/DAVEY ALLISON labels",
        ],
// 23. White cab, white container, black base, "Richard Petty" with portrait labels (WR)
	['mod' => $subtitle, 'var' => '23a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Richard Petty', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, RICHARD PETTY with portrait labels",
        ],
// 24. Dark blue cab, white container, black base, "Penn State 1855-1991" labels (WR)
	['mod' => $subtitle, 'var' => '24a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Penn State', 'cod' => '2', 'rar' => '',
            'cdt' => 'dark blue',
            'tdt' => "white container, black base, PENN STATE 1855-1991 labels",
        ],
// 25. White cab, white container, black base, "Trop Artie" with "Lake Speed" labels (WR)
	['mod' => $subtitle, 'var' => '25a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Trop Artic', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, TROP ARTIC with LAKE SPEED labels",
        ],
// 26. Blue cab, blue container, black base, "Maxwell House Racing" labels (WR)
	['mod' => $subtitle, 'var' => '26a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Maxwell House', 'cod' => '2', 'rar' => '',
            'cdt' => 'blue',
            'tdt' => "blue container, black base, MAXWELL HOUSE RACING labels",
        ],
// 27. White cab, white container, black base, "Ken Schraeder 25" labels (WR)
	['mod' => $subtitle, 'var' => '27a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Ken Schraeder', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, KEN SCHRAEDER 25 labels",
        ],
// 28. Orange-yellow cab, orange-yellow container, black base, "Kodak Racing" labels (WR)
	['mod' => $subtitle, 'var' => '28a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Kodak', 'cod' => '2', 'rar' => '',
            'cdt' => 'orange-yellow',
            'tdt' => "orange-yellow container, black base, KODAK RACING labels",
        ],
// 29. White cab, white container, black base, "Purolator" with red car labels (WR)
	['mod' => $subtitle, 'var' => '29a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Purolator', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, PUROLATOR with red car labels",
        ],
// 30. White cab, white container, black base, "Purolator" with orange car labels (WR)
	['mod' => $subtitle, 'var' => '30a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Purolator', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, PUROLATOR with orange car labels",
        ],
// 31. White cab, white container, black base, "Western Auto 17" labels (WR)
	['mod' => $subtitle, 'var' => '31a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Western Auto', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, WESTERN AUTO 17 labels",
        ],
// 32. White cab, white container, black base, "Country Time" labels (WR)
	['mod' => $subtitle, 'var' => '32a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Country Time', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, COUNTRY TIME labels",
        ],
// 33. Black cab, black container, black base, "MAC Tools" labels (WR)
	['mod' => $subtitle, 'var' => '33a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'MAC Tools', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, MAC TOOLS labels",
        ],
// 34. Black cab, black container, black base, "Mello Yello 42" labels (WR)
	['mod' => $subtitle, 'var' => '34a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Mello Yello', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, MELLO YELLO 42 labels",
        ],
// 35. Black cab, black container, black base, "Alliance" labels (WR)
	['mod' => $subtitle, 'var' => '35a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Alliance', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, ALLIANCE labels",
        ],
// 36. Yellow cab, yellow container, black base, "Pennzoil 2" labels (IN)
	['mod' => $subtitle, 'var' => '36a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Pennzoil', 'cod' => '1', 'rar' => '',
            'cdt' => 'yellow',
            'tdt' => "yellow container, black base, PENNZOIL 2 labels",
        ],
// 37. White cab, white container, black base, "Panasonic" labels (IN)
	['mod' => $subtitle, 'var' => '37a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Panasonic', 'cod' => '1', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, PANASONIC labels",
        ],
// 38. White cab, white container, black base, "K-Mart/Havoline" labels
	['mod' => $subtitle, 'var' => '38a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'K-Mart', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, K-MART/HAVOLINE labels",
        ],
// 39. Yellow cab, yellow container, black base, "Pennzoil" (Waltrip) labels (WR)
	['mod' => $subtitle, 'var' => '39a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Pennzoil', 'cod' => '2', 'rar' => '',
            'cdt' => 'yellow',
            'tdt' => "yellow container, black base, PENNZOIL (Waltrip) labels",
        ],
// 40. White cab, white container, black base, "STP-Richard Petty Fan Appreciation Tour 1992" labels (WR)
	['mod' => $subtitle, 'var' => '40a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'STP', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, STP-RICHARD PETTY FAN APPRECIATION TOUR 1992 labels",
        ],
// 41. White cab, white container, black base, "Baby Ruth Racing" labels 
	['mod' => $subtitle, 'var' => '41a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Baby Ruth', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, BABY RUTH RACING labels",
        ],
// 42. Black cab, black container, black base, "Goodwrench Racing Team" with checkered flags labels (WR)
	['mod' => $subtitle, 'var' => '42a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Goodwrench', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, GOODWRENCH RACING TEAM with checkered flags labels",
        ],
// 43. Metallic blue body, blue container, black base, "Raybestos" labels (WR)
	['mod' => $subtitle, 'var' => '43a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Raybestos', 'cod' => '2', 'rar' => '',
            'cdt' => 'metallic blue',
	    'tdt' => "blue container, black base, RAYBESTOS labels",
        ],
// 44. Black cab, red container, black base, "Slim Jim Racing Team" labels (WR)
	['mod' => $subtitle, 'var' => '44a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Slim Jim', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "red container, black base, SLIM JIM RACING TEAM labels",
        ],
// 45. White and green cab, white container, black base, "Quaker State" labels (WR)
	['mod' => $subtitle, 'var' => '45a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Quaker State', 'cod' => '2', 'rar' => '',
            'cdt' => 'white and green',
            'tdt' => "white container, black base, QUAKER STATE labels",
        ],
// 46. Blue and white cab, blue container, black base, "Evinrude 89" labels (WR)
	['mod' => $subtitle, 'var' => '46a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Evinrude', 'cod' => '2', 'rar' => '',
            'cdt' => 'blue and white',
            'tdt' => "blue container, black base, EVINRUDE 89 labels",
        ],
// 47. White cab, white container, black base, "Jasper Engines 55" labels (WR)
	['mod' => $subtitle, 'var' => '47a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Jasper Engines', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, JASPER ENGINES 55 labels",
        ],
// 48. Black cab, black container, black base, "MAC Tools Racing" (Harry Gant) labels (WR)
	['mod' => $subtitle, 'var' => '48a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'MAC Tools', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, MAC TOOLS RACING (Harry Gant) labels",
        ],
// 49. Black cab, black container, black base, "Martin Birrane-Team Ireland" labels 
	['mod' => $subtitle, 'var' => '49a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Team Ireland', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, MARTIN BIRRANE-TEAM IRELAND labels",
        ],
// 50. White cab, white container, black base, "Penn State Nittany Lions-Happy Valley Express" labels (WR)
	['mod' => $subtitle, 'var' => '50a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Penn State', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, PENN STATE NITTANY LIONS-HAPPY VALLEY EXPRESS labels",
        ],
// 51. Black cab, black container, black base, "Chevrolet Racing" (bowtie) labels (WR)
	['mod' => $subtitle, 'var' => '51a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Chevrolet', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, CHEVROLET RACING (bowtie) labels",
        ],
// 52. Black cab, black container, black base, "Moly Black Gold 98 Racing" labels (WR)
	['mod' => $subtitle, 'var' => '52a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Molly Black Gold', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, MOLY BLACK GOLD 98 RACING labels",
        ],
// 53. Blue cab, blue container, black base, "Sunoco Ultra 98" (LaBonte) labels (WR)
	['mod' => $subtitle, 'var' => '53a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Sunoco', 'cod' => '2', 'rar' => '',
            'cdt' => 'blue',
            'tdt' => "blue container, black base, SUNOCO ULTRA 98 (LaBonte) labels",
        ],
// 54. White cab, white container, black base, "Baby Ruth Racing" (Burton) labels (WR)
	['mod' => $subtitle, 'var' => '54a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Baby Ruth', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, BABY RUTH RACING (Burton) labels",
        ],
// 55. White cab, white container, black base, "Mackenzie Indy Racing" labels (IN)
	['mod' => $subtitle, 'var' => '55a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Mackenzie', 'cod' => '1', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, MACKENZIE INDY RACING labels",
        ],
// 56. White and blue cab, white container, black base, "Valvoline Racing" with "Goodyear" labels (IN)
	['mod' => $subtitle, 'var' => '56a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Valvoline', 'cod' => '1', 'rar' => '',
            'cdt' => 'white and blue',
            'tdt' => "white container, black base, VALVOLINE RACING with GOODYEAR labels",
        ],
// 57. Black cab, black container, black base, "Alliance 59" (2nd issue) labels (WR)
	['mod' => $subtitle, 'var' => '57a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Alliance', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, ALLIANCE 59 (2nd issue) labels",
        ],
// 58. Black cab, black container, black base, "Dirt Devil" labels (WR)
	['mod' => $subtitle, 'var' => '58a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Dirt Devil', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, DIRT DEVIL labels",
        ],
// 59. Metallic blue cab, blue container, black base, "Dupont Racing Team 24" labels (WR)
	['mod' => $subtitle, 'var' => '59a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Dupont', 'cod' => '2', 'rar' => '',
            'cdt' => 'metallic blue',
            'tdt' => "blue container, black base, DUPONT RACING TEAM 24 labels",
        ],
// 60. Red cab, red container, black base, "Dentyne Racing" labels (WR)
	['mod' => $subtitle, 'var' => '60a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Dentyne', 'cod' => '2', 'rar' => '',
            'cdt' => 'red',
            'tdt' => "red container, black base, DENTYNE RACING labels",
        ],
// 61. Black cab, black container, black base, "Meineke Racing Team 12" labels (WR)
	['mod' => $subtitle, 'var' => '61a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Meineke', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, MEINEKE RACING TEAM 12 labels",
        ],
// 62. Orange cab, orange container, black base, "Reithoffer's Antique Carousel" labels (WR)(GS)
	['mod' => $subtitle, 'var' => '62a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => "Reithoffer's", 'cod' => '1', 'rar' => '',
            'cdt' => 'orange',
            'tdt' => "orange container, black base, REITHOFFER'S ANTIQUE CAROUSEL labels",
        ],
// 63. Blue cab, blue container, black base, "Maxwell House" (B. LaBonte) labels 
	['mod' => $subtitle, 'var' => '63a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Maxwell House', 'cod' => '2', 'rar' => '',
            'cdt' => 'blue',
            'tdt' => "blue container, black base, MAXWELL HOUSE (B. LaBonte) labels",
        ],
// 64. Black cab, black container, black base, "Mac Tools/Davey Allison" labels (WR)
	['mod' => $subtitle, 'var' => '64a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'MAC Tools', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, MAC TOOLS/DAVEY ALLISON labels",
        ],
// 65. Red cab, red container, black base, "King of Speed-Mac Tools" labels (WR)
	['mod' => $subtitle, 'var' => '65a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'MAC Tools', 'cod' => '2', 'rar' => '',
            'cdt' => 'red',
            'tdt' => "red container, black base, KING OF SPEED-MAC TOOLS labels",
        ],
// 66. Red cab, white container, black base, "Indiana University-Go Big Red" labels (WR)
	['mod' => $subtitle, 'var' => '66a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Indiana University', 'cod' => '2', 'rar' => '',
            'cdt' => 'red',
            'tdt' => "white container, black base, INDIANA UNIVERSITY-GO BIG RED labels",
        ],
// 67. White cab, blue container, black base, "Raybestos 8" labels (WR)
	['mod' => $subtitle, 'var' => '67a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Raybestos', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "blue container, black base, RAYBESTOS 8 labels",
        ],
// 68. Orange-red cab, black container, black base, "Staff America Racing" labels (WR)
	['mod' => $subtitle, 'var' => '68a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Staff America', 'cod' => '2', 'rar' => '',
            'cdt' => 'orange-red',
            'tdt' => "black container, black base, STAFF AMERICA RACING labels",
        ],
// 69. Black cab, black container, black base, "Bojangles Racing Team" labels (WR)
	['mod' => $subtitle, 'var' => '69a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Bojangles', 'cod' => '2', 'rar' => '',
            'cdt' => 'black',
            'tdt' => "black container, black base, BOJANGLES RACING TEAM labels",
        ],
// 70. Gold and blue cab, dark blue container, black base, "Penn State 1993" labels (WR)
	['mod' => $subtitle, 'var' => '70a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Penn State', 'cod' => '2', 'rar' => '',
            'cdt' => 'gold and blue',
            'tdt' => "dark blue container, black base, PENN STATE 1993 labels",
        ],
// 71. White cab, white container, black base, "Dupont 99" labels (WR)
	['mod' => $subtitle, 'var' => '71a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Dupont', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, DUPONT 99 labels",
        ],
// 72. Red cab, red container, black base, "Nastrak" labels (WR)(GS)
	['mod' => $subtitle, 'var' => '72a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Nastrak', 'cod' => '1', 'rar' => '',
            'cdt' => 'red',
            'tdt' => "red container, black base, NASTRAK labels",
        ],
// 73. Blue cab, yellow container, black base, "Mannheim" labels (WR)
	['mod' => $subtitle, 'var' => '73a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'Mannheim', 'cod' => '2', 'rar' => '',
            'cdt' => 'blue',
            'tdt' => "yellow container, black base, MANNHEIM labels",
        ],
// 74. White cab, white container, black base, "Veh Vereinigte Getran-keebetriebe Cottbus" labels (C2)
	['mod' => $subtitle, 'var' => '74a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => '', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, VEH VEREINIGTE GETRAN-KEEBETRIEBE COTTBUS labels",
        ],
// 75. White cab, white container, black base, "8th European MICA Convention" labels (C2)
	['mod' => $subtitle, 'var' => '75a',
	    'cab' => 'MB103', 'tlr' => 'Superstar Transporter', 'mfg' => 'Thailand',
	    'liv' => 'MICA', 'cod' => '2', 'rar' => '',
            'cdt' => 'white',
            'tdt' => "white container, black base, 8TH EUROPEAN MICA CONVENTION labels",
        ],
    ]);
}
?>
