<?php // DONE
$subtitle = 'CY109A';
// CY-109-A FORD AEROMAX SUPERSTAR TRANSPORTER, issued 1991
$desc = "Ford Aeromax Superstar Transporter";
$year = '1991';
include "cypage.php";

function body() {
    global $subtitle;

// NOTE: All models with 8-spoke wheels and no antennas cast unless otherwise noted.
    show_table([
// 1. Gold cab, gold container, "Folgers" labels (WR)
	['mod' => $subtitle, 'var' => '01a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Folgiers', 'cod' => '2', 'rar' => '',
	    'cdt' => 'gold',
            'tdt' => "gold container, FOLGERS labels",
        ],
// 2. Blue cab, white container, "Bill Elliot 9" labels (WR)
	['mod' => $subtitle, 'var' => '02a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Bill Elliot', 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue',
            'tdt' => "white container, BILL ELLIOT 9 labels",
        ],
// 3. White cab, white container, "Hooters Racing" labels (WR)
	['mod' => $subtitle, 'var' => '03a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Hooters', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, HOOTERS RACING labels",
        ],
// 4. Black cab, black container, "Texaco Havoline/Davey Allison" labels (WR)
	['mod' => $subtitle, 'var' => '04a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Texaco', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "black container, TEXACO HAVOLINE/DAVEY ALLISON labels",
        ],
// 5. White cab, dark blue container, "Goodyear Racing" labels (WR)
	['mod' => $subtitle, 'var' => '05a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Goodyear', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "dark blue container, GOODYEAR RACING labels",
        ],
// 6. Red cab, red container, "Melling Performance 9" labels (WR)
	['mod' => $subtitle, 'var' => '06a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Melling Performance', 'cod' => '2', 'rar' => '',
	    'cdt' => 'red',
            'tdt' => "red container, MELLING PERFORMANCE 9 labels",
        ],
// 7. Red cab, red container, "Motorcraft" labels (WR)
	['mod' => $subtitle, 'var' => '07a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Motorcraft', 'cod' => '2', 'rar' => '',
	    'cdt' => 'red',
            'tdt' => "red container, MOTORCRAFT labels",
        ],
// 8. White cab, dark blue container, "Penn State Nittany Lions" labels (WR)
	['mod' => $subtitle, 'var' => '08a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Penn State', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "dark blue container, PENN STATE NITTANY LIONS labels",
        ],
// 9. Red-brown cab, red-brown container, "Washington Redskins Super Bowl Champions" labels (WR)
	['mod' => $subtitle, 'var' => '09a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'red-brown',
            'tdt' => "red-brown container, WASHINGTON REDSKINS SUPER BOWL CHAMPIONS labels",
        ],
// 10. White cab, white container, "Snickers Racing Team" labels (WR)
	['mod' => $subtitle, 'var' => '10a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Snickers', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, SNICKERS RACING TEAM labels",
        ],
// 11. Black cab, black container, "Stanley Mechanic Tools 92" labels (WR)
	['mod' => $subtitle, 'var' => '11a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Stanley', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "black container, STANLEY MECHANIC TOOLS 92 labels",
        ],
// 12. Green cab, red container, "Merry Christmas White Rose Collectibles 1992" labels (WR)
	['mod' => $subtitle, 'var' => '12a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'White Rose', 'cod' => '2', 'rar' => '',
	    'cdt' => 'green',
            'tdt' => "red container, MERRY CHRISTMAS WHITE ROSE COLLECTIBLES 1992 labels",
        ],
// 13. Blue cab, blue container, "Matchbox 29 Racing" labels (WR)
	['mod' => $subtitle, 'var' => '13a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Matchbox', 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue',
            'tdt' => "blue container, MATCHBOX 29 RACING labels",
        ],
// 14. White cab, white container, "Purex" labels (WR)
	['mod' => $subtitle, 'var' => '14a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Purex', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, PUREX labels",
        ],
// 15. Red cab, white container, "Wood Brothers-Citgo" labels (WR)
	['mod' => $subtitle, 'var' => '15a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Citgo', 'cod' => '2', 'rar' => '',
	    'cdt' => 'red',
            'tdt' => "white container, WOOD BROTHERS-CITGO labels",
        ],
// 16. Yellow cab, yellow container, "Matchbox Hong Kong Men of the Years 1982-1992" tempa (HK)
	['mod' => $subtitle, 'var' => '16a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Matchbox', 'cod' => '1', 'rar' => '',
	    'cdt' => 'yellow',
            'tdt' => "yellow container, MATCHBOX HONG KONG MEN OF THE YEARS 1982-1992 tempa",
        ],
// 17. Black cab, black container, "54th All Star Game" labels (WR)
	['mod' => $subtitle, 'var' => '17a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'MLB', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "black container, 54TH ALL STAR GAME labels",
        ],
// 18. Black cab, turquoise container, "1993 Florida Marlins" labels (WR)
	['mod' => $subtitle, 'var' => '18a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'MLB', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "turquoise container, 1993 FLORIDA MARLINS labels",
        ],
// 19. Black cab, purple container, "1993 Colorado Rockies" labels (WR)
	['mod' => $subtitle, 'var' => '19a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'MLB', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "purple container, 1993 COLORADO ROCKIES labels",
        ],
// 20. Silver-gray cab, dark blue container, "Cowboys Super Bowl Champions" labels (WR)
	['mod' => $subtitle, 'var' => '20a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray',
            'tdt' => "dark blue container, COWBOYS SUPER BOWL CHAMPIONS labels",
        ],
// 21. Orange cab, orange container "Reithoffer's Thunderbolt" labels (WR)(GS)
	['mod' => $subtitle, 'var' => '21a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => "Reithoffer's", 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange',
            'tdt' => "orange container REITHOFFER'S THUNDERBOLT labels",
        ],
// 22. Black cab, black container, "Virginia is for Lovers 25" labels (WR)
	['mod' => $subtitle, 'var' => '22a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Virginia', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "black container, VIRGINIA IS FOR LOVERS 25 labels",
        ],
// 23. Black cab, red container, "Falcons 1993" labels (WR)
	['mod' => $subtitle, 'var' => '23a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "red container, FALCONS 1993 labels",
        ],
// 24. Black cab, black container, "Steelers 1993" labels (WR)
	['mod' => $subtitle, 'var' => '24a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "black container, STEELERS 1993 labels",
        ],
// 25. White cab, blue container, "Patriots 1993" labels (WR)
	['mod' => $subtitle, 'var' => '25a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "blue container, PATRIOTS 1993 labels",
        ],
// 26. White cab, purple container, "Vikings 1993" labels (WR)
	['mod' => $subtitle, 'var' => '26a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "purple container, VIKINGS 1993 labels",
        ],
// 27. White cab, red container, "Oilers 1993" labels (WR)
	['mod' => $subtitle, 'var' => '27a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "red container, OILERS 1993 labels",
        ],
// 28. White cab, red container, "Buccaneers 1993" labels (WR)
	['mod' => $subtitle, 'var' => '28a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "red container, BUCCANEERS 1993 labels",
        ],
// 29. White cab, orange container, "Broncos 1993" labels (WR)
	['mod' => $subtitle, 'var' => '29a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "orange container, BRONCOS 1993 labels",
        ],
// 30. White cab, blue container, "Rams 1993" labels (WR)
	['mod' => $subtitle, 'var' => '30a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "blue container, RAMS 1993 labels",
        ],
// 31. Orange cab, black container, "Bengals 1993" labels (WR)
	['mod' => $subtitle, 'var' => '31a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange',
            'tdt' => "black container, BENGALS 1993 labels",
        ],
// 32. Orange cab, brown container, "Browns 1993" labels (WR)
	['mod' => $subtitle, 'var' => '32a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange',
            'tdt' => "brown container, BROWNS 1993 labels",
        ],
// 33. Red cab, blue container, "Bills 1993" labels (WR)
	['mod' => $subtitle, 'var' => '33a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'red',
            'tdt' => "blue container, BILLS 1993 labels",
        ],
// 34. Red cab, yellow container, "KC Chiefs 1993" labels (WR)
	['mod' => $subtitle, 'var' => '34a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'red',
            'tdt' => "yellow container, KC CHIEFS 1993 labels",
        ],
// 35. Red-brown cab, yellow container, "Redskins 1993" labels (WR)
	['mod' => $subtitle, 'var' => '35a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'red-brown',
            'tdt' => "yellow container, REDSKINS 1993 labels",
        ],
// 36. Red-brown cab, white container, "Cardinals 1993" labels (WR)
	['mod' => $subtitle, 'var' => '36a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'red-brown',
            'tdt' => "white container, CARDINALS 1993 labels",
        ],
// 37. Green-gold cab, black container, "Saints 1993" labels (WR)
	['mod' => $subtitle, 'var' => '37a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'green-gold',
            'tdt' => "black container, SAINTS 1993 labels",
        ],
// 38. Gold cab, gold container, "49ers 1993" labels (WR)
	['mod' => $subtitle, 'var' => '38a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'gold',
            'tdt' => "gold container, 49ERS 1993 labels",
        ],
// 39. Blue-green cab, orange container, "Dolphins 1993" labels (WR)
	['mod' => $subtitle, 'var' => '39a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue-green',
            'tdt' => "orange container, DOLPHINS 1993 labels",
        ],
// 40. Green cab, black container, "Jets 1993" labels (WR)
	['mod' => $subtitle, 'var' => '40a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'green',
            'tdt' => "black container, JETS 1993 labels",
        ],
// 41. Green cab, white container, "Eagles 1993" labels (WR)
	['mod' => $subtitle, 'var' => '41a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'green',
            'tdt' => "white container, EAGLES 1993 labels",
        ],
// 42. Dull green cab, yellow container, "Packers 1993" labels (WR)
	['mod' => $subtitle, 'var' => '42a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'dull green',
            'tdt' => "yellow container, PACKERS 1993 labels",
        ],
// 43. Blue cab, red container, "Giants 1993" labels (WR)
	['mod' => $subtitle, 'var' => '43a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue',
            'tdt' => "red container, GIANTS 1993 labels",
        ],
// 44. Blue cab, white container, "Colts 1993" labels (WR)
	['mod' => $subtitle, 'var' => '44a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue',
            'tdt' => "white container, COLTS 1993 labels",
        ],
// 45. Dark blue cab, orange container, "Bears 1993" labels (WR)
	['mod' => $subtitle, 'var' => '45a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue',
            'tdt' => "orange container, BEARS 1993 labels",
        ],
// 46. Dark blue cab, yellow container, "Chargers 1993" labels (WR)
	['mod' => $subtitle, 'var' => '46a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue',
            'tdt' => "yellow container, CHARGERS 1993 labels",
        ],
// 47. Silver-gray cab, green container, "Seahawks 1993" labels (WR)
	['mod' => $subtitle, 'var' => '47a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray',
            'tdt' => "green container, SEAHAWKS 1993 labels",
        ],
// 48. Silver-gray cab, blue container, "Lions 1993" labels (WR)
	['mod' => $subtitle, 'var' => '48a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray',
            'tdt' => "blue container, LIONS 1993 labels",
        ],
// 49. Silver-gray cab, dark blue container, "Cowboys 1993" labels (WR)
	['mod' => $subtitle, 'var' => '49a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray',
            'tdt' => "dark blue container, COWBOYS 1993 labels",
        ],
// 50. Silver-gray cab, black container, "Raiders 1993" labels (WR)
	['mod' => $subtitle, 'var' => '50a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'NFL', 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray',
            'tdt' => "black container, RAIDERS 1993 labels",
        ],
// 51. Black and red cab, black container, "Cappio" labels (WR)
	['mod' => $subtitle, 'var' => '51a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Cappio', 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and red',
            'tdt' => "black container, CAPPIO labels",
        ],
// 52. Yellow cab, yellow container, "Dewalt 08-B. Dotter" labels (WR)
	['mod' => $subtitle, 'var' => '52a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Dewalt', 'cod' => '2', 'rar' => '',
	    'cdt' => 'yellow',
            'tdt' => "yellow container, DEWALT 08-B. DOTTER labels",
        ],
// 53. White and blue cab, white container, "Valvoline" labels (WR)
	['mod' => $subtitle, 'var' => '53a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Valvoline', 'cod' => '2', 'rar' => '',
	    'cdt' => 'white and blue',
            'tdt' => "white container, VALVOLINE labels",
        ],
// 54. Sea green cab, white container, "Matchbox Road Museum" labels (WR)
	['mod' => $subtitle, 'var' => '54a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
            'liv' => 'Matchbox', 'cod' => '2', 'rar' => '',
	    'cdt' => 'sea green',
            'tdt' => "white container, MATCHBOX ROAD MUSEUM labels",
        ],
// 55. Orange-red cab, orange-red container, "Parcel Post Australia" labels (AU)
	['mod' => $subtitle, 'var' => '55a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Parcel Post', 'cod' => '1', 'rar' => '',
	    'cdt' => 'orange-red',
            'tdt' => "orange-red container, PARCEL POST AUSTRALIA labels",
        ],
// 56. White cab, white container, "Proball Paintball" labels (US)
	['mod' => $subtitle, 'var' => '56a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Proball', 'cod' => '1', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, PROBALL PAINTBALL labels",
        ],
// 57. White cab, white container, "Fastway Couriers" labels (AU)
	['mod' => $subtitle, 'var' => '57a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'Fastway', 'cod' => '1', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, FASTWAY COURIERS labels",
        ],
// 58. White cab, white container, "Gold Coast Rollers" labels (AU)
	['mod' => $subtitle, 'var' => '58a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, GOLD COAST ROLLERS labels",
        ],
// 59. White cab, white container, "Newcastle Falcons" labels (AU)
	['mod' => $subtitle, 'var' => '59a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, NEWCASTLE FALCONS labels",
        ],
// 60. White cab, white container, "Wildcats" labels (AU)
	['mod' => $subtitle, 'var' => '60a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, WILDCATS labels",
        ],
// 61. White cab, white container, "Illawarra Hawks" labels (AU)
	['mod' => $subtitle, 'var' => '61a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, ILLAWARRA HAWKS labels",
        ],
// 62. White cab, white container, "Brisbane Bullets" labels (AU)
	['mod' => $subtitle, 'var' => '62a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'white',
            'tdt' => "white container, BRISBANE BULLETS labels",
        ],
// 63. White and purple cab, white container, "Sydney Kings" labels (AU)
	['mod' => $subtitle, 'var' => '63a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'white and purple',
            'tdt' => "white container, SYDNEY KINGS labels",
        ],
// 64. Orange cab, white container, "Townsville Suns" labels (AU)
	['mod' => $subtitle, 'var' => '64a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'orange',
            'tdt' => "white container, TOWNSVILLE SUNS labels",
        ],
// 65. Orange-red cab, orange-red container, "Canberra Cannons" labels (AU)
	['mod' => $subtitle, 'var' => '65a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'orange-red',
            'tdt' => "orange-red container, CANBERRA CANNONS labels",
        ],
// 66. Red cab, dark blue container, "Geelong Supercats" labels (AU)
	['mod' => $subtitle, 'var' => '66a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'red',
            'tdt' => "dark blue container, GEELONG SUPERCATS labels",
        ],
// 67. Green cab, green container, "Devils" labels (AU)
	['mod' => $subtitle, 'var' => '67a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'green',
            'tdt' => "green container, DEVILS labels",
        ],
// 68. Blue-green cab, blue-green container, "North Melbourne Giants" labels (AU)
	['mod' => $subtitle, 'var' => '68a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'blue-green',
            'tdt' => "blue-green container, NORTH MELBOURNE GIANTS labels",
        ],
// 69. Blue cab, blue container, "Adelaide 36ers" labels (AU)
	['mod' => $subtitle, 'var' => '69a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'blue',
            'tdt' => "blue container, ADELAIDE 36ERS labels",
        ],
// 70. Black cab, black container, "Magic" labels (AU)
	['mod' => $subtitle, 'var' => '70a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "black container, MAGIC labels",
        ],
// 71. Black cab, black container, "Melbourne Tigers" labels (AU)
	['mod' => $subtitle, 'var' => '71a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => 'NBL', 'cod' => '1', 'rar' => '',
	    'cdt' => 'black',
            'tdt' => "black container, MELBOURNE TIGERS labels",
        ],
    ]);
}
?>
