<?php // DONE
$subtitle = 'CY113A';
// CY-113-A FORD AEROMAX SUPERSTAR TRANSPORTER, issued 1994
$desc = "Ford Aeromax Superstar Transporter";
$year = '1994';
include "cypage.php";

function body() {
    global $subtitle;

    show_table([
// 1. Metallic blue cab with blue chassis, blue container, "Family Channel" labels (WR)
	['mod' => $subtitle, 'var' => '001a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Family Channel", 'cod' => '2', 'rar' => '',
	    'cdt' => 'metallic blue, blue chassis',
	    'tdt' => "blue container, FAMILY CHANNEL labels",
        ],
// 2. Blue cab with red chassis, blue container, "Quality Care Racing" labels (WR)
	['mod' => $subtitle, 'var' => '002a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Quality Care Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue, red chassis',
	    'tdt' => "blue container, QUALITY CARE RACING labels",
	],
// 3. White cab with white chassis, white container, "7 Exide Batteries" labels (WR)
	['mod' => $subtitle, 'var' => '003a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "7 Exide Batteries", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white, white chassis',
	    'tdt' => "white container, 7 EXIDE BATTERIES labels",
	],
// 4. White cab with white chassis, white container, "Hooters Racing" labels (WR)
	['mod' => $subtitle, 'var' => '004a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Hooters Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white, white chassis',
	    'tdt' => "white container, HOOTERS RACING labels",
	],
// 5. Black cab with chrome chassis, black container, "Finger-hut Racing" labels (WR)
	['mod' => $subtitle, 'var' => '005a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Finger-hut Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black, chrome chassis',
	    'tdt' => "black container, FINGER-HUT RACING labels",
	],
// 6. White cab with chrome chassis, blue container, "Colts 94" labels (WR)
	['mod' => $subtitle, 'var' => '006a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Colts 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white, chrome chassis',
	    'tdt' => "blue container, COLTS 94 labels",
	],
// 7. White cab with chrome chassis, light blue container, "Oilers 94" labels (WR)
	['mod' => $subtitle, 'var' => '007a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Oilers 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white, chrome chassis',
	    'tdt' => "light blue container, OILERS 94 labels",
	],
// 8. White cab with chrome chassis, dark blue container, "Chargers 94" labels (WR)
	['mod' => $subtitle, 'var' => '008a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Chargers 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white, chrome chassis',
	    'tdt' => "dark blue container, CHARGERS 94 labels",
	],
// 9. White cab with chrome chassis, black container, "Raiders 94" labels (WR)
	['mod' => $subtitle, 'var' => '009a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Raiders 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white, chrome chassis',
	    'tdt' => "black container, RAIDERS 94 labels",
	],
// 10. White cab with chrome chassis, red container, "Bills 94" labels (WR)
	['mod' => $subtitle, 'var' => '010a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Bills 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white, chrome chassis',
	    'tdt' => "red container, BILLS 94 labels",
	],
// 11. Yellow cab with chrome chassis, red container, "Cardinals 94" labels (WR)
	['mod' => $subtitle, 'var' => '011a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Cardinals 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'yellow, chrome chassis',
	    'tdt' => "red container, CARDINALS 94 labels",
	],
// 12. Yellow cab with chrome chassis, red container, "KC Chiefs 94" labels (WR)
	['mod' => $subtitle, 'var' => '012a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "KC Chiefs 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'yellow, chrome chassis',
	    'tdt' => "red container, KC CHIEFS 94 labels",
	],
// 13. Yellow cab with chrome chassis, green container, "Packers 94" labels (WR)
	['mod' => $subtitle, 'var' => '013a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Packers 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'yellow, chrome chassis',
	    'tdt' => "green container, PACKERS 94 labels",
	],
// 14. Yellow cab with chrome chassis, black container, "Steelers 94" labels (WR)
	['mod' => $subtitle, 'var' => '014a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Steelers 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'yellow, chrome chassis',
	    'tdt' => "black container, STEELERS 94 labels",
	],
// 15. Orange cab with chrome chassis, red container, "Buccaneers 94" labels (WR)
	['mod' => $subtitle, 'var' => '015a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Buccaneers 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange, chrome chassis',
	    'tdt' => "red container, BUCCANEERS 94 labels",
	],
// 16. Orange cab with chrome chassis, white container, "Browns 94" labels (WR)
	['mod' => $subtitle, 'var' => '016a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Browns 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange, chrome chassis',
	    'tdt' => "white container, BROWNS 94 labels",
	],
// 17. Orange cab with chrome chassis, white container, "Bengals 94" labels (WR)
	['mod' => $subtitle, 'var' => '017a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Bengals 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange, chrome chassis',
	    'tdt' => "white container, BENGALS 94 labels",
	],
// 18. Orange cab with chrome chassis, turquoise container, "Dolphins 94" labels (WR)
	['mod' => $subtitle, 'var' => '018a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Dolphins 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange, chrome chassis',
	    'tdt' => "turquoise container, DOLPHINS 94 labels",
	],
// 19. Red-brown cab with chrome chassis, yellow container, "Redskins 94" labels (WR)
	['mod' => $subtitle, 'var' => '019a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Redskins 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red-brown, chrome chassis',
	    'tdt' => "yellow container, REDSKINS 94 labels",
	],
// 20. Red cab with chrome chassis, dark blue container, "Patriots 94" labels (WR)
	['mod' => $subtitle, 'var' => '020a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Patriots 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red, chrome chassis',
	    'tdt' => "dark blue container, PATRIOTS 94 labels",
	],
// 21. Red cab with chrome chassis, black container, "Falcons 94" labels (WR)
	['mod' => $subtitle, 'var' => '021a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Falcons 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red, chrome chassis',
	    'tdt' => "black container, FALCONS 94 labels",
	],
// 22. Silver-gray cab with chrome chassis, dark blue container, "Cowboys 94" labels (WR)
	['mod' => $subtitle, 'var' => '022a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Cowboys 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray, chrome chassis',
	    'tdt' => "dark blue container, COWBOYS 94 labels",
	],
// 23. Gold cab with chrome chassis, red container, "SF 49ers" labels (WR)
	['mod' => $subtitle, 'var' => '023a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "SF 49ers", 'cod' => '2', 'rar' => '',
	    'cdt' => 'gold, chrome chassis',
	    'tdt' => "red container, SF 49ERS labels",
	],
// 24. Green-gold cab with chrome chassis, black container, "Saints 94" labels (WR)
	['mod' => $subtitle, 'var' => '024a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Saints 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'green-gold, chrome chassis',
	    'tdt' => "black container, SAINTS 94 labels",
	],
// 25. Purple cab with chrome chassis, yellow container, "Vikings" labels (WR)
	['mod' => $subtitle, 'var' => '025a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Vikings", 'cod' => '2', 'rar' => '',
	    'cdt' => 'purple, chrome chassis',
	    'tdt' => "yellow container, VIKINGS labels",
	],
// 26. Dark blue cab with chrome chassis, white container, "Giants 94" labels (WR)
	['mod' => $subtitle, 'var' => '026a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Giants 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue, chrome chassis',
	    'tdt' => "white container, GIANTS 94 labels",
	],
// 27. Dark blue cab with chrome chassis, orange container, "Bears 94" labels (WR)
	['mod' => $subtitle, 'var' => '027a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Bears 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue, chrome chassis',
	    'tdt' => "orange container, BEARS 94 labels",
	],
// 28. Bright blue cab with chrome chassis, orange container, "Broncos 94" labels (WR)
	['mod' => $subtitle, 'var' => '028a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Broncos 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'bright blue, chrome chassis',
	    'tdt' => "orange container, BRONCOS 94 labels",
	],
// 29. Blue cab with chrome chassis, yellow container, "Rams 94" labels (WR)
	['mod' => $subtitle, 'var' => '029a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Rams 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue, chrome chassis',
	    'tdt' => "yellow container, RAMS 94 labels",
	],
// 30. Blue cab with chrome chassis, gray container, "Lions 94" labels (WR)
	['mod' => $subtitle, 'var' => '030a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Lions 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue, chrome chassis',
	    'tdt' => "gray container, LIONS 94 labels",
	],
// 31. Green cab with chrome chassis, gray container, "Eagles 94" labels (WR)
	['mod' => $subtitle, 'var' => '031a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Eagles 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'green, chrome chassis',
	    'tdt' => "gray container, EAGLES 94 labels",
	],
// 32. Green cab with chrome chassis, white container, "Jets 94" labels (WR)
	['mod' => $subtitle, 'var' => '032a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Jets 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'green, chrome chassis',
	    'tdt' => "white container, JETS 94 labels",
	],
// 33. Bright green cab with chrome chassis, gray container, "Seahawks 94" labels (WR)
	['mod' => $subtitle, 'var' => '033a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Seahawks 94", 'cod' => '2', 'rar' => '',
	    'cdt' => 'bright green, chrome chassis',
	    'tdt' => "gray container, SEAHAWKS 94 labels",
	],
// 34. Red cab and chassis, red container, "McDonald's Racing Team" labels (WR)
	['mod' => $subtitle, 'var' => '034a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "McDonald's Racing Team", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red cab and chassis',
	    'tdt' => "red container, MCDONALD'S RACING TEAM labels",
	],
// 35. Green cab with yellow chassis, green container, "Quaker State Racing Team" labels (WR)
	['mod' => $subtitle, 'var' => '035a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Quaker State Racing Team", 'cod' => '2', 'rar' => '',
	    'cdt' => 'green, yellow chassis',
	    'tdt' => "green container, QUAKER STATE RACING TEAM labels",
	],
// 36. Blue and yellow cab with yellow chassis, blue container, "Team Lowe's Racing" labels (WR)
	['mod' => $subtitle, 'var' => '036a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Team Lowe's Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and yellow, yellow chassis',
	    'tdt' => "blue container, TEAM LOWE'S RACING labels",
	],
// 37. Black cab and chassis, black container, "Helig-Myers" labels (WR)
	['mod' => $subtitle, 'var' => '037a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Helig-Myers", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black cab and chassis',
	    'tdt' => "black container, HELIG-MYERS labels",
	],
// 38. White and blue cab with blue chassis, blue container, "Valvoline Rousch Racing" labels (WR)
	['mod' => $subtitle, 'var' => '038a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Valvoline Rousch Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white and blue, blue chassis',
	    'tdt' => "blue container, VALVOLINE ROUSCH RACING labels",
	],
// 39. Metallic blue cab with blue chassis, blue container, "Raybestos Racing" labels (WR)
	['mod' => $subtitle, 'var' => '039a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Raybestos Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'metallic blue, blue chassis',
	    'tdt' => "blue container, RAYBESTOS RACING labels",
	],
// 40. Black cab with chrome chassis, black container, "Havoline" labels (WR)
	['mod' => $subtitle, 'var' => '040a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Havoline", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black, chrome chassis',
	    'tdt' => "black container, HAVOLINE labels",
	],
// 41. Black cab and chassis, black container, "Winn Dixie Racing" labels (WR)
	['mod' => $subtitle, 'var' => '041a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Winn Dixie Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black cab and chassis',
	    'tdt' => "black container, WINN DIXIE RACING labels",
	],
// 42. Red cab and chassis, red container, "Happy Holidays" labels (WR)
	['mod' => $subtitle, 'var' => '042a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Happy Holidays", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red cab and chassis',
	    'tdt' => "red container, HAPPY HOLIDAYS labels",
	],
// 43. Blue cab with lemon chassis, blue container, "Kleenex Racing 40" labels (WR)
	['mod' => $subtitle, 'var' => '043a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Kleenex Racing 40", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue, lemon chassis',
	    'tdt' => "blue container, KLEENEX RACING 40 labels",
	],
// 44. Red cab with gold chassis and wheels, red container, Ail-Star Game 1996" labels (WR)
	['mod' => $subtitle, 'var' => '044a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "All-Star Game 1996", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red, gold chassis and wheels',
	    'tdt' => "red container, ALL-STAR GAME 1996 labels",
	],
// 45. White cab and chassis, white container, "K-Mart/Little Caesars" labels (WR)
	['mod' => $subtitle, 'var' => '045a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "K-Mart/Little Caesars", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white cab and chassis',
	    'tdt' => "white container, K-MART/LITTLE CAESARS labels",
	],
// 46. White cab with red chassis, white container, "Jasper Engines and Transmissions" labels (WR)
	['mod' => $subtitle, 'var' => '046a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Jasper Engines and Transmissions", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white, red chassis',
	    'tdt' => "white container, JASPER ENGINES AND TRANSMISSIONS labels",
	],
// 47. Red and black cab with red chassis, red container, "McDonald's Racing" with two-line "McDonald's" roof label (WR)
	['mod' => $subtitle, 'var' => '047a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "McDonald's", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red and black, red chassis',
	    'tdt' => "red container, MCDONALD'S RACING with two-line MCDONALD'S roof label",
	],
// 48. Blue cab with orange chassis, blue container, "Team ASE" labels (WR)
	['mod' => $subtitle, 'var' => '048a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Team ASE", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue, orange chassis',
	    'tdt' => "blue container, TEAM ASE labels",
	],
// 49. Orange cab with blue chassis, orange container, "Florida Gators 96" labels (WR)
	['mod' => $subtitle, 'var' => '049a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Florida Gators 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange, blue chassis',
	    'tdt' => "orange container, FLORIDA GATORS 96 labels",
	],
// 50. Dark blue and yellow cab with yellow chassis, dark blue container, "Michigan 96" labels (WR)
	['mod' => $subtitle, 'var' => '050a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Michigan 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and yellow, yellow chassis',
	    'tdt' => "dark blue container, MICHIGAN 96 labels",
	],
// 51. White and red cab with black chassis, red container, "Nebraska Huskers 96" labels (WR)
	['mod' => $subtitle, 'var' => '051a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Nebraska Huskers 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white and red, black chassis',
	    'tdt' => "red container, NEBRASKA HUSKERS 96 labels",
	],
// 52. White and orange cab with orange chassis, orange container, "Syracuse University Orangemen 96" labels (WR)
	['mod' => $subtitle, 'var' => '052a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Syracuse University Orangemen 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white and orange, orange chassis',
	    'tdt' => "orange container, SYRACUSE UNIVERSITY ORANGEMEN 96 labels",
	],
// 53. Black cab with red chassis, red container, "Maryland Terrapins 96" labels (WR)
	['mod' => $subtitle, 'var' => '053a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Maryland Terrapins 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black, red chassis',
	    'tdt' => "red container, MARYLAND TERRAPINS 96 labels",
	],
// 54. Dark blue and white cab with white chassis, dark blue container, "Penn State Nittany Lions 96" labels (WR)
	['mod' => $subtitle, 'var' => '054a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Penn State Nittany Lions 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and white, white chassis',
	    'tdt' => "dark blue container, PENN STATE NITTANY LIONS 96 labels",
	],
// 55. Pale orange cab with chrome chassis, black container, "Super Bowl XXX" labels (WR)
	['mod' => $subtitle, 'var' => '055a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Super Bowl XXX", 'cod' => '2', 'rar' => '',
	    'cdt' => 'pale orange, chrome chassis',
	    'tdt' => "black container, SUPER BOWL XXX labels",
	],
// 56. Dark blue cab with red chassis, dark blue container, "Quality Care Ford Credit Racing" labels (WR)
	['mod' => $subtitle, 'var' => '056a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Quality Care Ford Credit Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue, red chassis',
	    'tdt' => "dark blue container, QUALITY CARE FORD CREDIT RACING labels",
	],
// 57. Dark blue cab and chassis, dark blue container, "Spam Racing" labels (WR)
	['mod' => $subtitle, 'var' => '057a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Spam Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue cab and chassis',
	    'tdt' => "dark blue container, SPAM RACING labels",
	],
// 58. White and dark blue cab with dark blue chassis, dark blue container, "Penn State 96" labels (WR)
	['mod' => $subtitle, 'var' => '058a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Penn State 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white and dark blue, dark blue chassis',
	    'tdt' => "dark blue container, PENN STATE 96 labels",
	],
// NOTE: All below models with chrome chassis
// 59. Dark blue and silver cab, gray container, "Patriots 96" labels (WR)
	['mod' => $subtitle, 'var' => '059a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Patriots 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and silver cab, chrome chassis',
	    'tdt' => "gray container, PATRIOTS 96 labels",
	],
// 60. Dark blue and silver cab, gray container, "Cowboys 1996" labels (WR)
	['mod' => $subtitle, 'var' => '060a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Cowboys 1996", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and silver cab, chrome chassis',
	    'tdt' => "gray container, COWBOYS 1996 labels",
	],
// 61. Dark blue and red cab, red container, "Giants 1996" labels (WR)
	['mod' => $subtitle, 'var' => '061a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Giants 1996", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and red cab, chrome chassis',
	    'tdt' => "red container, GIANTS 1996 labels",
	],
// 62. Dark blue and green cab, green container, "Seahawks 96" labels (WR)
	['mod' => $subtitle, 'var' => '062a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Seahawks 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and green cab, chrome chassis',
	    'tdt' => "green container, SEAHAWKS 96 labels",
	],
// 63. Dark blue and yellow cab, yellow container, "Chargers 1996" labels (WR)
	['mod' => $subtitle, 'var' => '063a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Chargers 1996", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and yellow cab, chrome chassis',
	    'tdt' => "yellow container, CHARGERS 1996 labels",
	],
// 64. Dark blue and yellow cab, yellow container, "Rams 96" labels (WR)
	['mod' => $subtitle, 'var' => '064a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Rams 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and yellow cab, chrome chassis',
	    'tdt' => "yellow container, RAMS 96 labels",
	],
// 65. Dark blue and orange cab, orange container, "Bears 96" labels (WR)
	['mod' => $subtitle, 'var' => '065a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Bears 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and orange cab, chrome chassis',
	    'tdt' => "orange container, BEARS 96 labels",
	],
// 66. Blue and silver cab, gray container, "Lions 96" labels (WR)
	['mod' => $subtitle, 'var' => '066a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Lions 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and silver cab, chrome chassis',
	    'tdt' => "gray container, LIONS 96 labels",
	],
// 67. Bright blue and orange cab, orange container, "Broncos 96" labels (WR)
	['mod' => $subtitle, 'var' => '067a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Broncos 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'bright blue and orange cab, chrome chassis',
	    'tdt' => "orange container, BRONCOS 96 labels",
	],
// 68. Bright blue and red cab, red container, "Bills 96" labels (WR)
	['mod' => $subtitle, 'var' => '068a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Bills 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'bright blue and red cab, chrome chassis',
	    'tdt' => "red container, BILLS 96 labels",
	],
// 69. Blue-green and orange cab, orange container, "Dolphins 96" labels (WR)
	['mod' => $subtitle, 'var' => '069a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Dolphins 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue-green and orange cab, chrome chassis',
	    'tdt' => "orange container, DOLPHINS 96 labels",
	],
// 70. Turquoise and mustard cab, mustard container, "Jacksonville Jaguars 96" labels (WR)
	['mod' => $subtitle, 'var' => '070a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Jacksonville Jaguars 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'turquoise and mustard cab, chrome chassis',
	    'tdt' => "mustard container, JACKSONVILLE JAGUARS 96 labels",
	],
// 71. Black and orange cab, orange container, "Bengals 96" labels (WR)
	['mod' => $subtitle, 'var' => '071a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Bengals 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and orange cab, chrome chassis',
	    'tdt' => "orange container, BENGALS 96 labels",
	],
// 72. Black and red cab, red container, "Falcons 96" labels (S8-12MWR)
	['mod' => $subtitle, 'var' => '072a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Falcons 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and red cab, chrome chassis',
	    'tdt' => "red container, FALCONS 96 labels",
	],
// 73. Black and silver cab, gray container, "Raiders 96" labels (S8-12)(WR)
	['mod' => $subtitle, 'var' => '073a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Raiders 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and silver cab, chrome chassis',
	    'tdt' => "gray container, RAIDERS 96 labels",
	],
// 74. Black and gold cab, gold container, "Saints 96" labels (S8-12)(WR)
	['mod' => $subtitle, 'var' => '074a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Saints 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and gold cab, chrome chassis',
	    'tdt' => "gold container, SAINTS 96 labels",
	],
// 75. Black and yellow cab, yellow container, "Steelers 96" labels (WR)
	['mod' => $subtitle, 'var' => '075a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Steelers 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and yellow cab, chrome chassis',
	    'tdt' => "yellow container, STEELERS 96 labels",
	],
// 76. Black and green cab, green container, "Jets 96" labels (S8-12)(WR)
	['mod' => $subtitle, 'var' => '076a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Jets 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and green cab, chrome chassis',
	    'tdt' => "green container, JETS 96 labels",
	],
// 77. Black and purple cab, purple container, "Ravens Inaugural Season 1996" labels (WR)
	['mod' => $subtitle, 'var' => '077a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Ravens Inaugural Season 1996", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and purple cab, chrome chassis',
	    'tdt' => "purple container, RAVENS INAUGURAL SEASON 1996 labels",
	],
// 78. black and blue cab, blue container, "Panthers 96" labels iS8-12)(WR)
	['mod' => $subtitle, 'var' => '078a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Panthers 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and blue cab, chrome chassis',
	    'tdt' => "blue container, PANTHERS 96 labels iS8-12)",
	],
// 79. Black and dark blue-green cab, dark blue-green container, "Eagles 96" labels (WR)
	['mod' => $subtitle, 'var' => '079a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Eagles 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and dark blue-green cab, chrome chassis',
	    'tdt' => "dark blue-green container, EAGLES 96 labels",
	],
// 80. Purple and yellow cab, yellow container, "Vikings 96" labels (S8-12)(WR)
	['mod' => $subtitle, 'var' => '080a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Vikings 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'purple and yellow cab, chrome chassis',
	    'tdt' => "yellow container, VIKINGS 96 labels",
	],
// 81. Green and yellow cab, yellow container, "Packers 96" labels (WR)
	['mod' => $subtitle, 'var' => '081a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Packers 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'green and yellow cab, chrome chassis',
	    'tdt' => "yellow container, PACKERS 96 labels",
	],
// 82. Rose and gold cab, gold container, "49ers 96" labels (WR)
	['mod' => $subtitle, 'var' => '082a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "49ers 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'rose and gold cab, chrome chassis',
	    'tdt' => "gold container, 49ERS 96 labels",
	],
// 83. Rose and yellow cab, yellow container, "Cardinals 96" labels (WR)
	['mod' => $subtitle, 'var' => '083a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Cardinals 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'rose and yellow cab, chrome chassis',
	    'tdt' => "yellow container, CARDINALS 96 labels",
	],
// 84. Rose and yellow cab, yellow container, "Redskins 96" labels (WR)
	['mod' => $subtitle, 'var' => '084a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Redskins 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'rose and yellow cab, chrome chassis',
	    'tdt' => "yellow container, REDSKINS 96 labels",
	],
// 85. Red and yellow cab, yellow container, "Chiefs 96" labels (WR)
	['mod' => $subtitle, 'var' => '085a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Chiefs 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red and yellow cab, chrome chassis',
	    'tdt' => "yellow container, CHIEFS 96 labels",
	],
// 86. Red and orange cab, orange container, "Buccaneers 96" labels (WR)
	['mod' => $subtitle, 'var' => '086a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Buccaneers 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red and orange cab, chrome chassis',
	    'tdt' => "orange container, BUCCANEERS 96 labels",
	],
// 87. Red and light blue cab, light blue container, "Oilers 96" labels (WR)
	['mod' => $subtitle, 'var' => '087a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Oilers 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red and light blue cab, chrome chassis',
	    'tdt' => "light blue container, OILERS 96 labels",
	],
// 88. White and dark blue cab, blue container, "Colts 96" labels (WR)
	['mod' => $subtitle, 'var' => '088a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Colts 96", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white and dark blue cab, chrome chassis',
	    'tdt' => "blue container, COLTS 96 labels",
	],
// 89. Black cab with chrome chassis, black container, "Associated Truck and Brake Supply" labels (WR)
	['mod' => $subtitle, 'var' => '089a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Associated Truck and Brake Supply", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black, chrome chassis',
	    'tdt' => "black container, ASSOCIATED TRUCK AND BRAKE SUPPLY labels",
	],
// 90. Black cab and chassis, black container, "Exide 99 Racing Team"(WR)
	['mod' => $subtitle, 'var' => '090a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Exide 99 Racing Team", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black cab and chassis',
	    'tdt' => "black container, EXIDE 99 RACING TEAM",
	],
// 91. Black cab, chrome chassis, black container, "Miller Lite Racing" labels (WR)
	['mod' => $subtitle, 'var' => '091a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Miller Lite Racing", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black cab, chrome chassis',
	    'tdt' => "black container, MILLER LITE RACING labels",
	],
// 92. Silver-gray cab, chrome chassis, gray container, "68th Ail-Star Game 1997" labels (WR)
	['mod' => $subtitle, 'var' => '092a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "68th Ail-Star Game 1997", 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray cab, chrome chassis',
	    'tdt' => "gray container, 68TH AIL-STAR GAME 1997 labels",
	],
// 93. White cab, chrome chassis, white container, "New Holland" labels (WR)
	['mod' => $subtitle, 'var' => '093a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "New Holland", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white cab, chrome chassis',
	    'tdt' => "white container, NEW HOLLAND labels",
	],
// 94. Blue and red cab, blue container, "1997 New England Patriots" labels (WR)
	['mod' => $subtitle, 'var' => '094a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and red cab, chrome chassis',
	    'tdt' => "blue container, 1997 NEW ENGLAND PATRIOTS labels",
	],
// 95. Blue and red cab, blue container, "1997 New York Giants" labels (WR)
	['mod' => $subtitle, 'var' => '095a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and red cab, chrome chassis',
	    'tdt' => "blue container, 1997 NEW YORK GIANTS labels",
	],
// 96. Blue and red cab, blue container, "1997 Buffalo Bills" labels (WR)
	['mod' => $subtitle, 'var' => '096a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and red cab, chrome chassis',
	    'tdt' => "blue container, 1997 BUFFALO BILLS labels",
	],
// 97. Blue and red cab, blue container, "1997 Atlanta Falcons" labels (WR)
	['mod' => $subtitle, 'var' => '097a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and red cab, chrome chassis',
	    'tdt' => "blue container, 1997 ATLANTA FALCONS labels",
	],
// 98. Blue and orange cab, blue container, "1997 Denver Broncos" labels (WR)
	['mod' => $subtitle, 'var' => '098a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and orange cab, chrome chassis',
	    'tdt' => "blue container, 1997 DENVER BRONCOS labels",
	],
// 99. Blue and yellow cab, blue container, "1997 San Diego Chargers" labels (WR)
	['mod' => $subtitle, 'var' => '099a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and yellow cab, chrome chassis',
	    'tdt' => "blue container, 1997 SAN DIEGO CHARGERS labels",
	],
// 100. Dark blue and orange cab, dark blue container, "1997 Cincinnati Bengals" labels (WR)
	['mod' => $subtitle, 'var' => '100a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and orange cab, chrome chassis',
	    'tdt' => "dark blue container, 1997 CINCINNATI BENGALS labels",
	],
// 101. Dark blue and yellow cab, dark blue container, "1997 St. Louis Rams" labels (WR)
	['mod' => $subtitle, 'var' => '101a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and yellow cab, chrome chassis',
	    'tdt' => "dark blue container, 1997 ST. LOUIS RAMS labels",
	],
// 102. Dark blue and orange cab, blue container, "1997 Chicago Bears" labels (WR)
	['mod' => $subtitle, 'var' => '102a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and orange cab, chrome chassis',
	    'tdt' => "blue container, 1997 CHICAGO BEARS labels",
	],
// 103. Dark blue and mustard cab, blue container, "1997 Baltimore Ravens" labels (WR)
	['mod' => $subtitle, 'var' => '103a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark blue and mustard cab, chrome chassis',
	    'tdt' => "blue container, 1997 BALTIMORE RAVENS labels",
	],
// 104. Blue and black cab, dark blue container, "1997 Indianapolis Colts" labels (WR)
	['mod' => $subtitle, 'var' => '104a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and black cab, chrome chassis',
	    'tdt' => "dark blue container, 1997 INDIANAPOLIS COLTS labels",
	],
// 105. Blue and green cab, blue container, "1997 Seattle Seahawks" labels (WR)
	['mod' => $subtitle, 'var' => '105a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue and green cab, chrome chassis',
	    'tdt' => "blue container, 1997 SEATTLE SEAHAWKS labels",
	],
// 106. Blue-green and mustard cab, blue-green container, "1997 Jacksonville Jaguars" labels (WR)
	['mod' => $subtitle, 'var' => '106a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue-green and mustard cab, chrome chassis',
	    'tdt' => "blue-green container, 1997 JACKSONVILLE JAGUARS labels",
	],
// 107. Blue-green and orange cab, blue-green container, "1997 Miami Dolphins" tampo (WR)
	['mod' => $subtitle, 'var' => '107a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue-green and orange cab, chrome chassis',
	    'tdt' => "blue-green container, 1997 MIAMI DOLPHINS tampo",
	],
// 108. Purple and yellow cab, purple container, "1997 Minnesota Vikings" labels (WR)
	['mod' => $subtitle, 'var' => '108a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'purple and yellow cab, chrome chassis',
	    'tdt' => "purple container, 1997 MINNESOTA VIKINGS labels",
	],
// 109. Black and silver-gray cab, black containers, "1997 Oakland Raiders" labels (WR)
	['mod' => $subtitle, 'var' => '109a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and silver-gray cab, chrome chassis',
	    'tdt' => "black containers, 1997 OAKLAND RAIDERS labels",
	],
// 110. Black and blue cab, black container, "1997 Carolina Panthers" labels (WR)
	['mod' => $subtitle, 'var' => '110a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and blue cab, chrome chassis',
	    'tdt' => "black container, 1997 CAROLINA PANTHERS labels",
	],
// 111. Black and dark green cab, black container, "1997 New York Jets" labels (WR)
	['mod' => $subtitle, 'var' => '111a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and dark green cab, chrome chassis',
	    'tdt' => "black container, 1997 NEW YORK JETS labels",
	],
// 112. Black and mustard cab, black container, "1997 New Orleans Saints" labels (WR)
	['mod' => $subtitle, 'var' => '112a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and mustard cab, chrome chassis',
	    'tdt' => "black container, 1997 NEW ORLEANS SAINTS labels",
	],
// 113. Black and yellow cab, black container, "1997 Pittsburgh Steelers" labels (WR)
	['mod' => $subtitle, 'var' => '113a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and yellow cab, chrome chassis',
	    'tdt' => "black container, 1997 PITTSBURGH STEELERS labels",
	],
// 114. Black and dark green cab, black container, "1997 Philadelphia Eagles" labels (WR)
	['mod' => $subtitle, 'var' => '114a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'black and dark green cab, chrome chassis',
	    'tdt' => "black container, 1997 PHILADELPHIA EAGLES labels",
	],
// 115. Dark green and yellow cab, dark green container, "1997 Green Bay Packers" labels (WR)
	['mod' => $subtitle, 'var' => '115a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark green and yellow cab, chrome chassis',
	    'tdt' => "dark green container, 1997 GREEN BAY PACKERS labels",
	],
// 116. Silver-gray and dark blue cab, blue container, "1997 Dallas Cowboys" labels (WR)
	['mod' => $subtitle, 'var' => '116a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray and dark blue cab, chrome chassis',
	    'tdt' => "blue container, 1997 DALLAS COWBOYS labels",
	],
// 117. Silver-gray and blue cab, gray container, "1997 Detroit Lions" labels (WR)
	['mod' => $subtitle, 'var' => '117a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'silver-gray and blue cab, chrome chassis',
	    'tdt' => "gray container, 1997 DETROIT LIONS labels",
	],
// 118. Red and yellow cab, red container, "1997 Kansas City Chiefs" labels (WR)
	['mod' => $subtitle, 'var' => '118a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red and yellow cab, chrome chassis',
	    'tdt' => "red container, 1997 KANSAS CITY CHIEFS labels",
	],
// 119. Red and blue cab, red container, "1997 Tennessee Oilers" labels (WR)
	['mod' => $subtitle, 'var' => '119a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'red and blue cab, chrome chassis',
	    'tdt' => "red container, 1997 TENNESSEE OILERS labels",
	],
// 120. Orange and red cab, red container, "1997 Tampa Bay Buccaneers" labels (WR)
	['mod' => $subtitle, 'var' => '120a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'orange and red cab, chrome chassis',
	    'tdt' => "red container, 1997 TAMPA BAY BUCCANEERS labels",
	],
// 121. Rose and yellow cab, rose container, "1997 Washington Redskins" labels (WR)
	['mod' => $subtitle, 'var' => '121a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'rose and yellow cab, chrome chassis',
	    'tdt' => "rose container, 1997 WASHINGTON REDSKINS labels",
	],
// 122. Rose and yellow cab, rose container, "1997 Arizona Cardinals" labels (WR)
	['mod' => $subtitle, 'var' => '122a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'rose and yellow cab, chrome chassis',
	    'tdt' => "rose container, 1997 ARIZONA CARDINALS labels",
	],
// 123. Rose and gold cab, red container, "1997 San Francisco 49ers" labels (WR)
	['mod' => $subtitle, 'var' => '123a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "NFL", 'cod' => '2', 'rar' => '',
	    'cdt' => 'rose and gold cab, chrome chassis',
	    'tdt' => "red container, 1997 SAN FRANCISCO 49ERS labels",
	],
// 124. Green and yellow cab, green container, "Packers Super Bowl XXXI" labels (WR)
	['mod' => $subtitle, 'var' => '124a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Packers Super Bowl XXXI", 'cod' => '2', 'rar' => '',
	    'cdt' => 'green and yellow cab, chrome chassis',
	    'tdt' => "green container, PACKERS SUPER BOWL XXXI labels",
	],
// 125. Blue cab, chrome chassis, white container, "Miller Lite" labels, sealed in plexibox (WR)
	['mod' => $subtitle, 'var' => '125a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Miller Lite", 'cod' => '2', 'rar' => '',
	    'cdt' => 'blue cab, chrome chassis',
	    'tdt' => "white container, MILLER LITE labels, sealed in plexibox",
	    'nts' => 'Sealed in plexibox',
	],
// 126. Dark red cab, chrome chassis, dark red container, "Circuit City 8" labels (WR)
	['mod' => $subtitle, 'var' => '126a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Circuit City 8", 'cod' => '2', 'rar' => '',
	    'cdt' => 'dark red cab, chrome chassis',
	    'tdt' => "dark red container, CIRCUIT CITY 8 labels",
	],
// 127. White cab and chassis, white container, "QVC Racing Team 7" labels (WR)
	['mod' => $subtitle, 'var' => '127a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "QVC Racing Team 7", 'cod' => '2', 'rar' => '',
	    'cdt' => 'white cab and chassis',
	    'tdt' => "white container, QVC RACING TEAM 7 labels",
	],
// 128. Green cab, chrome chassis, red container, "Merry Christmas Happy New Year- White Rose Collectibles 1997" labels (WR)
	['mod' => $subtitle, 'var' => '128a',
	    'cab' => 'MB214', 'tlr' => 'Superstar Transporter', 'mfg' => 'Macau',
	    'liv' => "Merry Christmas Happy New Year- White Rose Collectibles 1997", 'cod' => '2', 'rar' => '',
	    'cdt' => 'green cab, chrome chassis',
	    'tdt' => "red container, MERRY CHRISTMAS HAPPY NEW YEAR- WHITE ROSE COLLECTIBLES 1997 labels",
	],
    ]);
}
?>
