<?php // DONE
$subtitle = 'CY114A';
$desc = "Tractor Cab with Finshbelly";
$year = '2005';
include "cypage.php";

function body() {
    global $subtitle;

    show_table([
	['mod' => $subtitle, 'var' => '01a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'China',
	    'liv' => 'Jeep', 'cod' => '1', 'rar' => '',
            'cdt' => 'black',
            'tdt' => 'black, JEEP',
	    'nts' => '2005 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '02a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'China',
	    'liv' => 'Sonic', 'cod' => '1', 'rar' => '',
            'cdt' => 'pearly white',
            'tdt' => 'pearly white, SONIC',
	    'nts' => '2005 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '03a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'China',
	    'liv' => 'Yu-Gi-Oh', 'cod' => '1', 'rar' => '',
            'cdt' => 'dark blue',
            'tdt' => 'dark blue, YU-GI-OH',
	    'nts' => '2005 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '04a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Yamaha', 'cod' => '1', 'rar' => '',
            'cdt' => 'black',
            'tdt' => 'black, YAMAHA',
	    'nts' => '2006 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '05a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Good Year', 'cod' => '1', 'rar' => '',
            'cdt' => 'lemon',
            'tdt' => 'dark blue, JEEP',
	    'nts' => '2006 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '06a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Mario Kart', 'cod' => '1', 'rar' => '',
            'cdt' => 'red',
            'tdt' => 'yellow, MARIOKART',
	    'nts' => '2006 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '07a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Land Rover', 'cod' => '1', 'rar' => '',
            'cdt' => 'black',
            'tdt' => 'black, LAND ROVER G4',
	    'nts' => '2006 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '08a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Matchbox', 'cod' => '1', 'rar' => '',
            'cdt' => 'black, tan chassis',
            'tdt' => 'black, MATCHBOX',
	    'nts' => "2005 Convoy Wheels - Mummy's Gold Set",
	],
	['mod' => $subtitle, 'var' => '09a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => '"M" Construction', 'cod' => '1', 'rar' => '',
            'cdt' => 'dark yellow',
            'tdt' => 'dark yellow, M CONSTRUCTION',
	    'nts' => '2005 Convoy Wheels - Construction Set',
	],
	['mod' => $subtitle, 'var' => '10a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'McDonalds', 'cod' => '1', 'rar' => '',
            'cdt' => 'red',
            'tdt' => 'red, MCDONALDS',
	],
	['mod' => $subtitle, 'var' => '11a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Yamaha', 'cod' => '1', 'rar' => '',
            'cdt' => 'blue',
            'tdt' => 'blue, YAMAHA',
	],
	['mod' => $subtitle, 'var' => '12a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'McDonalds', 'cod' => '1', 'rar' => '',
            'cdt' => 'lemon',
            'tdt' => 'blue, MCDONALDS',
	],
	['mod' => $subtitle, 'var' => '13a',
	    'cab' => 'MB664', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Matchbox', 'cod' => '1', 'rar' => '',
            'cdt' => 'beige',
            'tdt' => 'dark green, MATCHBOX',
	],
    ]);
}
?>
