<?php // DONE
$subtitle = 'CY115A';
$desc = "Ford Aeromax with Fishbelly";
$year = '2005';
include "cypage.php";

function body() {
    global $subtitle;

    show_table([
	['mod' => $subtitle, 'var' => '01a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'Macau',
	    'liv' => 'DHL ', 'cod' => '1', 'rar' => '',
            'cdt' => 'yellow',
            'tdt' => 'yellow, DHL',
	    'nts' => '2005 Convoy Wheels ',
	],
	['mod' => $subtitle, 'var' => '02a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'Macau',
	    'liv' => 'Michelin', 'cod' => '1', 'rar' => '',
            'cdt' => 'dark blue',
            'tdt' => 'dark blue, MICHELIN',
	    'nts' => '2005 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '03a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'Macau',
	    'liv' => 'McDonalds', 'cod' => '1', 'rar' => '',
            'cdt' => 'red',
            'tdt' => 'red, MCDONALDS',
	    'nts' => '2005 Convoy Wheels ',
	],
	['mod' => $subtitle, 'var' => '04a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'Macau',
	    'liv' => 'DHL ', 'cod' => '1', 'rar' => '',
            'cdt' => 'yellow',
            'tdt' => 'yellow, DHL',
	    'nts' => '2006 Convoy Wheels ',
	],
	['mod' => $subtitle, 'var' => '05a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'Macau',
	    'liv' => 'Michelin', 'cod' => '1', 'rar' => '',
            'cdt' => 'dark blue',
            'tdt' => 'dark blue, MICHELIN',
	    'nts' => '2006 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '06a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'McDonalds', 'cod' => '1', 'rar' => '',
            'cdt' => 'red',
            'tdt' => 'red, MCDONALDS',
	    'nts' => '2006 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '07a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Land Rover G4', 'cod' => '1', 'rar' => '',
            'cdt' => 'white',
            'tdt' => 'white, LAND ROVER G4 CHALLENGE',
	    'nts' => '2006 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '08a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'Thailand',
	    'liv' => 'Honey Nut Cherrios', 'cod' => '1', 'rar' => '',
            'cdt' => '',
            'tdt' => '',
	    'nts' => '2006 Convoy Wheels',
	],
	['mod' => $subtitle, 'var' => '09a',
	    'cab' => 'MB214', 'tlr' => 'Fishbelly', 'mfg' => 'China',
	    'liv' => 'Firestone Racing', 'cod' => '1', 'rar' => '',
            'cdt' => 'white',
            'tdt' => 'white, FIRESTONE RACING',
	    'nts' => '2006 Convoy Wheels',
	],
    ]);
}
?>
