<?php

$dat = [
  1953 => [
    "1953" => "https://matchbox.fandom.com/wiki/List_of_1953_Matchbox",
    "Matchbox_Series" => "MB",
  ],
  1954 => [
    "1954" => "https://matchbox.fandom.com/wiki/List_of_1954_Matchbox",
    "Matchbox_Series" => "MB",
  ],
  1955 => [
    "1955" => "https://matchbox.fandom.com/wiki/List_of_1955_Matchbox",
    "Matchbox_Series" => "MB",
  ],
  1956 => [
    "1956" => "https://matchbox.fandom.com/wiki/List_of_1956_Matchbox",
    "Matchbox_Series_Nos_1_to_29" => "MB",
    "Accesory_Packs" => "AP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1957 => [
    "1957" => "https://matchbox.fandom.com/wiki/List_of_1957_Matchbox",
    "Matchbox_Series_No._1-42" => "MB",
    "Accesory_Packs" => "AP",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1958 => [
    "1958" => "https://matchbox.fandom.com/wiki/List_of_1958_Matchbox",
    "Accessory_Packs" => "AP",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1959 => [
    "1959" => "https://matchbox.fandom.com/wiki/List_of_1959_Matchbox",
    "Matchbox_Series_1-75" => "MB",
    "Accessory_Packs" => "AP",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1960 => [
    "1960" => "https://matchbox.fandom.com/wiki/List_of_1960_Matchbox",
    "Series_1-75" => "MB",
    "Accessory_Packs" => "AP",
    "King_Size" => "KS",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1961 => [
    "1961" => "https://matchbox.fandom.com/wiki/List_of_1961_Matchbox",
    "Series_1-75" => "MB",
    "Accessory_Packs" => "AP",
    "King_Size" => "KS",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1962 => [
    "1962" => "https://matchbox.fandom.com/wiki/List_of_1962_Matchbox",
    "Series_1-75" => "MB",
    "Accessory_Packs" => "AP",
    "King_Size" => "KS",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1963 => [
    "1963" => "https://matchbox.fandom.com/wiki/List_of_1963_Matchbox",
    "Series_1-75" => "MB",
    "Accessory_Packs" => "AP",
    "King_Size" => "KS",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1964 => [
    "1964" => "https://matchbox.fandom.com/wiki/List_of_1964_Matchbox",
    "1-75_Series" => "MB",
    "Accessory_Packs" => "AP",
    "King_Size" => "KS",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1965 => [
    "1965" => "https://matchbox.fandom.com/wiki/List_of_1965_Matchbox",
    "Series_1-75" => "MB",
    "Accessory_Packs" => "AP",
    "King_Size" => "KS",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1966 => [
    "1966" => "https://matchbox.fandom.com/wiki/List_of_1966_Matchbox",
    "Series_1-75" => "MB",
    "Accessory_Packs" => "AP",
    "King_Size" => "KS",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1967 => [
    "1967" => "https://matchbox.fandom.com/wiki/List_of_1967_Matchbox",
    "Series_1-75" => "MB",
    "Accessory_Packs" => "AP",
    "King_Size" => "KS",
    "Major_Packs" => "MP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1968 => [
    "1968" => "https://matchbox.fandom.com/wiki/List_of_1968_Matchbox",
    "Series_1-75" => "MB",
    "King_Size" => "KS",
    "Models_of_Yesteryear" => "MOY",
  ],
  1969 => [
    "1969" => "https://matchbox.fandom.com/wiki/List_of_1969_Matchbox",
    "Matchbox_Series_Nos._1-75" => "MB",
    "King_Size" => "KS",
    "Models_of_Yesteryear" => "MOY",
  ],
  1970 => [
    "1970" => "https://matchbox.fandom.com/wiki/List_of_1970_Matchbox",
    "Series_1-75" => "MB",
    "King_Size" => "KS",
    "Models_of_Yesteryear" => "MOY",
  ],
  1971 => [
    "1971" => "https://matchbox.fandom.com/wiki/List_of_1971_Matchbox",
    "1-75_series" => "MB",
    "Super_Kings" => "SK",
    "Speed_Kings" => "SpK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1972 => [
    "1972" => "https://matchbox.fandom.com/wiki/List_of_1972_Matchbox",
    "1-75_Series" => "MB",
    "Super_Kings" => "SK",
    "Speed_Kings" => "SpK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1973 => [
    "1973" => "https://matchbox.fandom.com/wiki/List_of_1973_Matchbox",
    "Series_1-75" => "MB",
    "Super_Kings" => "SK",
    "Speed_Kings" => "SpK",
    "Sky_Busters" => "SB",
    "Models_of_Yesteryear" => "MOY",
  ],
  1974 => [
    "1974" => "https://matchbox.fandom.com/wiki/List_of_1974_Matchbox",
    "1-75_Series" => "MB",
    "Super_Kings" => "SK",
    "Speed_Kings" => "SpK",
    "Battle_Kings" => "BK",
    "Sky_Busters" => "SB",
    "Models_of_Yesteryear" => "MOY",
  ],
  1975 => [
    "1975" => "https://matchbox.fandom.com/wiki/List_of_1975_Matchbox",
    "Super_Kings" => "SK",
    "Speed_Kings" => "SpK",
    "Battle_Kings" => "BK",
    "Sky_Busters" => "SB",
    "Models_of_Yesteryear" => "MOY",
  ],
  1976 => [
    "1976" => "https://matchbox.fandom.com/wiki/List_of_1976_Matchbox",
    "1-75_Series" => "MB",
    "Super_Kings" => "SK",
    "Speed_Kings" => "SpK",
    "Battle_Kings" => "BK",
    "Sea_Kings" => "SeaK",
    "Sky_Busters" => "SB",
    "Models_of_Yesteryear" => "MOY",
  ],
  1977 => [
    "1977" => "https://matchbox.fandom.com/wiki/List_of_1977_Matchbox",
    "1-75_series" => "MB",
    "Super_Kings" => "SK",
    "Speed_Kings" => "SpK",
    "Battle_Kings" => "BK",
    "Sea_Kings" => "SeaK",
    "Adventure_2000" => "A2K",
    "Sky_Busters" => "SB",
    "Two_Packs" => "TP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1978 => [
    "1978" => "https://matchbox.fandom.com/wiki/List_of_1978_Matchbox",
    "Series_1-75" => "MB",
    "Super_Kings" => "SK",
    "Speed_Kings" => "SpK",
    "Battle_Kings" => "BK",
    "Sea_Kings" => "SeaK",
    "Adventure_2000" => "A2K",
    "Sky_Busters" => "SB",
    "Two_Packs" => "TP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1979 => [
    "1979" => "https://matchbox.fandom.com/wiki/List_of_1979_Matchbox",
    "Matchbox_75" => "MB",
    "900_Range" => "TP",
    "Super_Kings" => "SK",
    "Battle_Kings" => "BK",
    "Sea_Kings" => "SeaK",
    "Adventure_2000" => "A2K",
    "Sky_Busters" => "SB",
    "Models_of_Yesteryear" => "MOY",
  ],
  1980 => [
    "1980" => "https://matchbox.fandom.com/wiki/List_of_1980_Matchbox",
    "Series_1-75" => "MB",
    "900" => "TP",
    "Sky-Busters" => "SB",
    "Super_Kings" => "SK",
    "Battle_Kings" => "BK",
    "Sea_Kings" => "SeaK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1981 => [
    "1981" => "https://matchbox.fandom.com/wiki/List_of_1981_Matchbox",
    "1-75_series" => "MB",
    "Super_Kings" => "SK",
    "Battle_Kings" => "BK",
    "Adventure_2000" => "A2K",
    "Sky-Busters" => "SB",
    "900_Range" => "TP",
    "Models_of_Yesteryear" => "MOY",
  ],
  1982 => [
    "1982" => "https://matchbox.fandom.com/wiki/List_of_1982_Matchbox",
    "1-75_series" => "MB",
    "Convoys" => "CY",
    "SuperKings" => "SK",
    "Sky-Busters" => "SB",
    "Models_of_Yesteryear" => "MOY",
  ],
  1983 => [
    "1983" => "https://matchbox.fandom.com/wiki/List_of_1983_Matchbox",
    "1-75_Series" => "MB",
    "Convoy" => "CY",
    "Super_Kings" => "SK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1984 => [
    "1984" => "https://matchbox.fandom.com/wiki/List_of_1984_Matchbox",
    "1-75_range" => "MB",
    "Convoy" => "CY",
    "SuperKings" => "SK",
    "Skybusters" => "SB",
    "Specials" => "Spec",
    "Models_of_Yesteryear" => "MOY",
  ],
  1985 => [
    "1985" => "https://matchbox.fandom.com/wiki/List_of_1985_Matchbox",
    "1-75_Range" => "MB",
    "Convoy" => "CY",
    "Skybusters" => "SB",
    "Specials" => "Spec",
    "Models_of_Yesteryear" => "MOY",
  ],
  1986 => [
    "1986" => "https://matchbox.fandom.com/wiki/List_of_1986_Matchbox",
    "1-75_range" => "MB",
    "Convoy" => "CY",
    "Skybusters" => "SB",
    "Specials" => "Spec",
    "Superkings" => "SK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1987 => [
    "1987" => "https://matchbox.fandom.com/wiki/List_of_1987_Matchbox",
    "1-75_range" => "MB",
    "Convoy" => "CY",
    "Superkings" => "SK",
    "Skybusters" => "SB",
    "Specials" => "Spec",
    "Models_of_Yesteryear" => "MOY",
  ],
  1988 => [
    "1988" => "https://matchbox.fandom.com/wiki/List_of_1988_Matchbox",
    "1-75_Range" => "MB",
    "Convoys" => "CY",
    "Skybusters" => "SB",
    "Super_Kings" => "SK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1989 => [
    "1989" => "https://matchbox.fandom.com/wiki/List_of_1989_Matchbox",
    "1-75_Series" => "MB",
    "Convoys" => "CY",
    "Dinky_Collection" => "DY",
    "Super_Kings" => "SK",
    "Skybusters" => "SB",
    "Models_of_Yesteryear" => "MOY",
  ],
  1990 => [
    "1990" => "https://matchbox.fandom.com/wiki/List_of_1990_Matchbox",
    "1-75_Range" => "MB",
    "Convoy" => "CY",
    "Dinky_Collection" => "DY",
    "Skybusters" => "SB",
    "Superkings" => "SK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1991 => [
    "1991" => "https://matchbox.fandom.com/wiki/List_of_1991_Matchbox",
    "1-75_Range" => "MB",
    "Construction" => "CS",
    "Convoy" => "CY",
    "Dinky_Collection" => "DY",
    "Emergency" => "EM",
    "Skybusters" => "SB",
    "Superkings" => "SK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1992 => [
    "1992" => "https://matchbox.fandom.com/wiki/List_of_1992_Matchbox",
    "1-75_range" => "MB",
    "Action_Farming" => "FM",
    "Construction" => "CS",
    "Convoy" => "CY",
    "Dinky_Collection" => "DY",
    "Emergency" => "EM",
    "Skybusters" => "SB",
    "Superkings" => "SK",
    "Models_of_Yesteryear" => "MOY",
  ],
  1993 => [
    "1993" => "https://matchbox.fandom.com/wiki/List_of_1993_Matchbox",
    "1-75_Range" => "MB",
  ],
  1994 => [
    "1994" => "https://matchbox.fandom.com/wiki/List_of_1994_Matchbox",
    "1-75_Series" => "MB",
    "Matchbox_Originals" => "MO",
  ],
  1995 => [
    "1995" => "https://matchbox.fandom.com/wiki/List_of_1995_Matchbox",
    "1-75_Series" => "MB",
  ],
  1996 => [
    "1996" => "https://matchbox.fandom.com/wiki/List_of_1996_Matchbox",
    "Models_of_Yesteryear" => "MOY",
  ],
  1997 => [
    "1997" => "https://matchbox.fandom.com/wiki/List_of_1997_Matchbox",
    "1-75_Range" => "MB",
    "Other_Series" => "Other",
  ],
  1998 => [
    "1998" => "https://matchbox.fandom.com/wiki/List_of_1998_Matchbox",
    "1-75_range" => "MB",
  ],
  1999 => [
    "1999" => "https://matchbox.fandom.com/wiki/List_of_1999_Matchbox",
    "1-100_Series" => "MB",
  ],
  2000 => [
    "2000" => "https://matchbox.fandom.com/wiki/List_of_2000_Matchbox",
    "1-100_series" => "MB",
  ],
  2001 => [
    "2001" => "https://matchbox.fandom.com/wiki/List_of_2001_Matchbox",
    "1-75_range" => "MB",
    "Coca-Cola_Series" => "CK",
    "Other_Series" => "Other",
  ],
  2002 => [
    "2002" => "https://matchbox.fandom.com/wiki/List_of_2002_Matchbox",
    "1-75_range" => "MB",
    "Matchbox_Across_America_50th_Birthday_Series" => "AAM",
    "Matchbox_Birthday_Hunts" => "BH",
    "Other_Series" => "Other",
  ],
  2003 => [
    "2003" => "https://matchbox.fandom.com/wiki/List_of_2003_Matchbox",
    "1-75_Series" => "MB",
  ],
  2004 => [
    "2004" => "https://matchbox.fandom.com/wiki/List_of_2004_Matchbox",
    "1-75_range" => "MB",
  ],
  2005 => [
    "2005" => "https://matchbox.fandom.com/wiki/List_of_2005_Matchbox",
    "1-75_Range" => "MB",
    "New_Superfast" => "NSF",
    "5-Packs" => "5P",
  ],
  2006 => [
    "2006" => "https://matchbox.fandom.com/wiki/List_of_2006_Matchbox",
    "1-75_series" => "MB",
  ],
  2007 => [
    "2007" => "https://matchbox.fandom.com/wiki/List_of_2007_Matchbox",
    "1-75_Series" => "MB",
    "Other_Series" => "Other",
  ],
  2008 => [
    "2008" => "https://matchbox.fandom.com/wiki/List_of_2008_Matchbox",
    "1_to_100_range" => "MB",
    "Additional_2008_releases" => "Other",
  ],
  2009 => [
    "2009" => "https://matchbox.fandom.com/wiki/List_of_2009_Matchbox",
    "See_also" => "Other",
  ],
  2010 => [
    "2010" => "https://matchbox.fandom.com/wiki/List_of_2010_Matchbox",
    "1-100_Series" => "MB",
    "5-Packs" => "5P",
    "Licensed_5-Packs" => "L5P",
    "10-Packs" => "10P",
    "Lesney_Editions" => "LE",
    "Real_Working_Rigs" => "RWR",
    "Super_Convoys" => "SCY",
  ],
  2011 => [
    "2011" => "https://matchbox.fandom.com/wiki/List_of_2011_Matchbox",
    "1-100_Series" => "MB",
    "Sky_Busters" => "SB",
    "Additional_2011_Releases" => "Other",
  ],
  2012 => [
    "2012" => "https://matchbox.fandom.com/wiki/List_of_2012_Matchbox",
    "1-120_Series" => "MB",
    "Additional_2012_Releases" => "Other",
  ],
  2013 => [
    "2013" => "https://matchbox.fandom.com/wiki/List_of_2013_Matchbox",
    "1-120_Series" => "MB",
    "See_also" => "Other",
  ],
  2014 => [
    "2014" => "https://matchbox.fandom.com/wiki/List_of_2014_Matchbox",
    "1-120_range" => "MB",
    "Other_series" => "Other",
  ],
  2015 => [
    "2015" => "https://matchbox.fandom.com/wiki/List_of_2015_Matchbox",
    "1-120_Series" => "MB",
    "See_also" => "Other",
  ],
  2016 => [
    "2016" => "https://matchbox.fandom.com/wiki/List_of_2016_Matchbox",
    "See_also" => "Other",
  ],
  2017 => [
    "2017" => "https://matchbox.fandom.com/wiki/List_of_2017_Matchbox",
    "1-125_Series" => "MB",
    "Other_Series" => "Other",
  ],
  2018 => [
    "2018" => "https://matchbox.fandom.com/wiki/List_of_2018_Matchbox",
    "1-125_Series" => "MB",
    "See_also" => "Other",
  ],
  2019 => [
    "2019" => "https://matchbox.fandom.com/wiki/List_of_2019_Matchbox",
    "1-100_Series" => "MB",
    "Other_Series" => "Other",
  ],
  2020 => [
    "2020" => "https://matchbox.fandom.com/wiki/List_of_2020_Matchbox",
    "1-100_Series" => "MB",
    "Other_Series" => "Other",
  ],
  2021 => [
    "2021" => "https://matchbox.fandom.com/wiki/List_of_2021_Matchbox",
    "1-100_Series" => "MB",
    "Other_Series" => "Other",
  ],
  2022 => [
    "2022" => "https://matchbox.fandom.com/wiki/List_of_2022_Matchbox",
    "1-102_Series" => "MB",
    "Other_Series" => "Other",
  ],
];
?>
